### ISSUE TITLE
Produce images without NuGet package cache

### ISSUE THREAD

**Issue by LordMike** [dotnet/dotnet-docker#1095]
### Feature request

Would it be possible for you to produce an image without the `dotnet help` ([link](https://github.com/dotnet/dotnet-docker/blob/4fd3b74fc5b7444f39f3fdcffa45eef467bccb24/2.2/sdk/bionic/amd64/Dockerfile#L37)) run in it?

We'd like to build on this image to produce our own custom version of the dotnet SDK, tailored for our CI where we amongst others mount the nuget directories to an outside folder. Not having this line would mean that we don't need to shuffle around 1.1 GB of extra (irrelevant) data.

**Comment by MichaelSimons** [comment]
To make sure I understand your scenario, your issue is not so much that `dotnet help` is run it is that the image contains the NuGet Package cache.   The issue of carrying a large package cache payload is being addressed in 3.0.  See https://github.com/dotnet/designs/pull/50 for details.  If you pull the latest 3.0 image `mcr.microsoft.com/dotnet/core/sdk:3.0` you will see the package cache is gone.  We would like to confirm this addresses your concern.

**Comment by LordMike** [comment]
I didn't read the entire thread, but if the package cache is gone (and some ingenious way is in place to acquire it quickly for those using the image "as normal" is in place), it'll solve my issue.

Will the recommendation be to mount the package cache somewhere, to reuse it?

**Comment by MichaelSimons** [comment]
The package cache is going away in-lieu of utilizing target packs (e.g. reference assemblies).  In the latest 3.0 preview images the targeting packs are ~60 MB.

**Comment by LordMike** [comment]
Very well. Thanks. :)
