### ISSUE TITLE
The 1.0.0 "SDK" image actually has .NET 1.0.1 installed

### ISSUE THREAD

**Issue by enyim** [dotnet/dotnet-docker#114]
## Steps to reproduce the issue
1. pull the latest `microsoft/docker:1.0.0-preview2-sdk` image
2. Or check commit 352ca3442fe43589f948f123d9fe2cbdb564e260

## Expected behavior

1.0.0 images should have .NET Core 1.0.0 installed

## Actual behavior

They have 1.0.1 installed

## Additional information (e.g. issue happens only occasionally)

I believe, no matter how backward compatible the .NET releases are, no matter what kind of bugs they fix, you should be using _new tags for new versions_, instead of overwriting previously published images.

Especially that 1.0.1 is not _totally_ backward compatible, as we have to update the `project.json` to make the project compile on 1.0.1. (As per https://github.com/dotnet/coreclr/releases/tag/v1.0.4)

And this is how I actually found out this: I tried to run a previously perfect image on a newly installed VM, which produced mysterious compile errors.

**Comment by naamunds** [comment]
Hi @enyim, to make sure we're on the same page here, can you please elaborate on the following statement:
> Especially that 1.0.1 is not _totally_ backward compatible, as we have to update the `project.json` to make the project compile on 1.0.1. (As per https://github.com/dotnet/coreclr/releases/tag/v1.0.4)

It is possible to compile and run a 1.0.0 project using the SDK released with .NET Core 1.0.1 (SDK version 1.0.0-preview2-003131) without modifying project.json or any other files; you may need to run `dotnet restore` first, though.

Also, what are the "mysterious compile errors" you're referring to?  A more detailed repro for this would be great.

**Comment by enyim** [comment]
Hi,

I had a similar issue as `poteb` here: https://blogs.msdn.microsoft.com/dotnet/2016/09/13/announcing-september-2016-updates-for-net-core-1-0/

> Can not find runtime target for framework ‘.NETCoreApp,Version=v1.0’ compatible with one of the target runtimes: ‘win10-x64, win81-x64, win8-x64, win7-x64’. Possible causes:

Unfortunately I have to work on the repro as my system is quite complex. I'll try to spend some time on it. Fixing the project json fixed the issue for me.

OTOH sorry about muddying the issue, my actual problem here is a red herring :) My point is that a published image should not change, as people depend on its content.

**Comment by naamunds** [comment]
The .NET Core SDK version in the `1.0.0-preview2-sdk` image tag changed because .NET released 1.0.0-preview2-003131 to replace 1.0.0-preview2-003121 as the current 1.0.0-preview2 release.

This repo does not provide image tags for specific .NET builds; the `1.0.0-preview2-sdk` image tracks the current .NET Core SDK release which is versioned 1.0.0-preview2, just as the `1.0-core` image tracks the current .NET Core release which is versioned 1.0 (whether 1.0.0, 1.01, etc.).

Also note that even if .NET isn't updated, there may be changes to underlying dependencies (e.g. to packages such as libcurl3) which will cause the image tag to be revved.

If you want to ensure that the image you are referencing does not change, you can consider referencing it [via digest](https://docs.docker.com/engine/reference/commandline/images/#/listing-image-digests) instead of via tag.  For example, you could use the following command to explicitly reference the 1.0.0-preview2-003121 SDK image:
`docker run microsoft/dotnet@sha256:e447a02d3b520adc7b0fa3294f33b833d5d170eb13d6a42d56edce3e467557d2`

(You can find the image digests in the build logs at https://hub.docker.com/r/microsoft/dotnet/builds/)
