### ISSUE TITLE
Unable to use mcr.microsoft.com/dotnet/core/sdk:2.2 for dotnet core application with angular | Node Needed

### ISSUE THREAD

**Issue by akashpavate58** [dotnet/dotnet-docker#1238]
## Steps to reproduce the issue
1.1. Create a ASP.NET Core 2.2 Web Application with Angular
1.2. Add an nUnit Test Project
2. Add .gitlab-ci.yml with contents below in the root of the project. Beside .sln

``` ".gitlab-ci.yml"
image: microsoft/aspnetcore-build:latest

stages:
    - build
    - test

variables:
    test: "TestCases"

before_script:
    - "cd GitLabBuild"
    - "dotnet restore"
    - ""
build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"
```

3. Commit to Gitlab Repo and watch the build

## Expected behavior
1. It should successfully build and test

## Actual behavior
1. dotnet restore works
2. dotnet build fails since the node PM is not installed

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
@akashpavate58 - Node is not in the `mcr.microsoft.com/dotnet/core/sdk` images.  This is a component that will need to be added in derived Dockerfiles that require it.  It is not included for a couple reasons.  First, it is not used by a large portion of the use cases.  Second, it is a component that can't be upgraded over the lifetime of a particular .NET version due to concerns about breaking changes.  Because of this, the version included would not be what everyone wants, therefore they would need to add their own version at which point the image would contain multiple versions.
