### ISSUE TITLE
Use build triggers

### ISSUE THREAD

**Issue by ahmetalpbalkan** [dotnet/dotnet-docker#14]
In aspnet image we use build trigger such as:

![image](https://cloud.githubusercontent.com/assets/159209/11324274/f89e9478-9124-11e5-85f4-2fe58199d7b1.png)

In case one debian/mono repos get rebuilt (such as security update) we get rebuilt, too. Please consider enabling that for this repo as well (see Build Settings tab) @dleeapho

**Comment by MichaelSimons** [comment]
There are two potential issue with using build triggers that we need to look out for.

1.  Previously, the CLI team was manually publishing the Debian packages to the repo after the package was signed off on.  This was not part of their automated build process.  We need to follow-up with them to see if their process has changed.  We could make use of a build trigger if need be.
2.  Docker does not have support for automatically rebuilding dependent images - https://forums.docker.com/t/automatic-re-build-of-depending-images/594.  This causes issues with the onbuild image.  It must be rebuilt after the base image is built.

**Comment by ahmetalpbalkan** [comment]
@MichaelSimons valid points but having this is better than nothing and I don't think onbuild image will be impacted with that. Simply if there's a newer build of `buildpack-deps:trusty-scm` all tags will be triggered to build again from source.

Our builds should be idempotent as in it should not matter when or how many times we're building these images. If there's a critical vulnerability in `buildpack-deps:trusty-scm`, we need to keep track of those otherwise and manually trigger a rebuild (which I don't think anybody would bother). Makes sense?

**Comment by MichaelSimons** [comment]
@ahmetalpbalkan, regarding the onbuild image.  This image is based on the Microsoft/dotnet:0.0.1-alpha image.  Because of this, the onbuild image must be rebuilt anytime the Microsoft/dotnet:0.0.1-alpha image if rebuilt.  More specific, it needs to be rebuilt after the Microsoft/dotnet:0.0.1-alpha image is built.  Docker build triggers cause the all images to get rebuilt concurrently.  This means the onbuild images produced by these build triggers are incorrect because they are based on the previously built Microsoft/dotnet:0.0.1-alpha image.  Again this appears to be a limitation Docker has on their backlog - https://forums.docker.com/t/automatic-re-build-of-depending-images/594

**Comment by MichaelSimons** [comment]
I added the appropriate repository links as part of https://github.com/dotnet/dotnet-docker/pull/36.
