### ISSUE TITLE
Define version-less floating tag for Debian

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1422]
There are version-specific tags for Debian (such as `buster` and `stretch`) but there is not a floating tag `debian` that would just give you the latest Debian release.  This is inconsistent with what is done with Alpine images where there is a floating `alpine` tag that points to the latest Alpine release.

**Comment by MichaelSimons** [comment]
We do not feel there is a common use case for this and therefore are not going to add a Debian floating tag.  We only support LTS versions of Debian and moving between LTS versions is not seamless.  The Alpine comparison is different because of the rapid pace of Alpine uptake in Docker images compared to Debian. 

In general we are conservative when adding additional tags as we have found that the more tags we produce the more difficult it is for users to decipher which tag best suits their needs.
