### ISSUE TITLE
msiexec.exe missing

### ISSUE THREAD

**Issue by rong0312** [dotnet/dotnet-docker#1448]
Greetings,  
I came across a situation in which I have to install an MSI.
Sadly, msiexec.exe does not exist inside **mcr.microsoft.com/dotnet/core/sdk:3.0**
I can't find and propper way to get this exe.  
Why it's missing anyway?! I believe its an important tool, especially for builds.

## Expected behavior

msiexec.exe installed under C:\Windows\System32

## Actual behavior
``
'msiexec' is not recognized as an internal or external command,
operable program or batch file.
``

**Comment by MichaelSimons** [comment]
@rong0312 - The .NET Core Windows images are based on Nano Server which is slimmed down and doesn't support MSI based installers.  Here is a snippet from a past [Windows Server blog post](https://cloudblogs.microsoft.com/windowsserver/2015/11/16/moving-to-nano-server-the-new-deployment-option-in-windows-server-2016/).

>Nano Server does not include MSI as an installation technology due to dependencies and the open ended nature of MSI custom actions. Instead, Nano Server has a new declarative Appx-based installer called Windows Server App (WSA) Installer.

Can you explain your scenario?  What you are trying to install?  It is possible to utilize a multi-stage build for your scenario?  By that I mean you could have a stage that uses a [Windows](https://hub.docker.com/_/microsoft-windows) or [Windows Server Core](https://hub.docker.com/_/microsoft-windows-servercore) based image that you install the MSI in.  You can then utilize the component within that stage or COPY the it into the Nano Server image.

**Comment by rong0312** [comment]
I wanted to install sqllocalDB.msi. As you said, I am about to use servercore as build image.
Thank you i will close this issue.

**Comment by brentarias** [comment]
> Windows Server App (WSA) Installer

You say that 'Windows Server Core' allows `msiexec`.  I have attempted that and it does not work.  See [this SO post](https://stackoverflow.com/questions/76369548/how-to-add-sqlcmd-to-a-docker-base-image), where I am unable to install `sqlcmd` within the image `mcr.microsoft.com/dotnet/aspnet:6.0-windowsservercore-ltsc2022`.

Ultimately, all I really want is to have `sqlcmd.exe` available within the image `mcr.microsoft.com/dotnet/aspnet:6.0`.  Perhaps I need to find a non-msi means to accomplish that (if that image does not support `msiexec`).  I want this because:
* The Entity Framework (EF) recommended way to execute DB-migrations is with a raw SQL script (presumably executed with the `sqlcmd.exe` tool...which supports `GO` statements within T-SQL statements). I concur with their advice, that other EF-migration patterns should not be used...that only the raw-SQL script approach should be pursued.
* I am ultimately building an Azure Marketplace app, which can only perform the DB-migration at run-time, rather than build-time or deploy-time.  This means that my Azure App Service (which uses `mcr.microsoft.com/dotnet/aspnet:6.0`) needs access to `sqlcmd` from its `[entrypoint]`.

Any suggestions of how I can get `sqlcmd` inside of `mcr.microsoft.com/dotnet/aspnet:6.0`?
