### ISSUE TITLE
Add `dotnet trace` tooling in base image?

### ISSUE THREAD

**Issue by curiousdev** [dotnet/dotnet-docker#1672]
Can we add vance's `dotnet trace` tooling to the `mcr.microsoft.com/dotnet/core/aspnet:3.1`?

Trying to do this manually in a `Dockerfile` results in:

```
Step 31/36 : RUN dotnet tool install --global dotnet-trace
 ---> Running in 78e25001ddc4
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

**Comment by MichaelSimons** [comment]
`dotnet trace` is packaged as a global tool therefore it requires the SDK to install.  We don't want to bloat the runtime targeted images with diagnostic tools like this.  We receive regular feedback from users on how important image size is.

I think the desired pattern is to run `dotnet trace` within a sidecar image.  I tried this and wasn't able to get it working.  I logged https://github.com/dotnet/diagnostics/issues/810 to track this.

**Comment by curiousdev** [comment]
That makes sense. Side car seems like a reasonable approach. Would dotnet be willing to issue a side-car image 'mcr.microsoft.com/dotnet/core/diagtools:3.1'? That way it lowers to barrier for others to trace their code.

**Comment by MichaelSimons** [comment]
@curiousdev, Your ask is an interesting one.  We would like to know how many users would make use of an image like you propose.  Creating another image and servicing it is not a trivial task so we want to make sure the cost is justified.  Would you open a separate issue specific to the diagnostic tools side car image so that we can solicit feedback from the community and discuss the value of it?  Thanks.
