### ISSUE TITLE
Dotnet restore takes a long time

### ISSUE THREAD

**Issue by FIVIL** [dotnet/dotnet-docker#1697]
Hey, I am trying to build an asp.net core website using dotnet core 3.1  and docker and I have encountered a somewhat peculiar behavior, I am not sure if this goes under the category of bugs though. 
I am using `mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim` base Image and the problem is the `RUN dotnet restore` step in Dockerfile takes a very long time to execute.
The whole process of pulling the base Image from MCR and extracting it takes roughly 5 to 10 seconds but restoring packages inside the container takes about a minute or so.
Also, these are the packages that I have installed in my project
Google.Protobuf
Grpc.AspNetCore
Grpc.Net.Client
Grpc.Net.ClientFactory
MongoDB.Driver
Newtonsoft.Json
Polly
Serilog.AspNetCore
Serilog.Sinks.Seq
StackExchange.Redis

**Comment by mthalman** [comment]
Is this Docker-specific?  Have you tried deleting the NuGet cache on your dev machine and run `dotnet restore` on your project to see how the performance compares?

**Comment by MichaelSimons** [comment]
@FIVIL - Can you explain your scenario a little more?  Are you rebuilding this dockerfile project frequently in a developer desktop type of scenario?  Is this an automated CI/CD type of scenario?

**Comment by FIVIL** [comment]
@mthalman So I cleared the cache and the Image in one of our machines and tried to build the container and it made things worst. The first time build failed during restoring the packages, the second time it was able to build the container successfully but it took even longer than before to restore the packages

**Comment by FIVIL** [comment]
@MichaelSimons Well I first notice the issue when I tried to run dotnet restore command on my local machine and it took less time to execute than in our CI/CD server. (bear in mind that my local machine has a significantly weaker network connection)
So I believe the problem happens only when it comes to containers.
PS: I am currently investigating the possibility of a poor network connection or firewall related problem in our CI/CD server. I am trying to build this container using other CI/CD pipelines such as azure and GitLab to see if this issue happens there. I will keep you informed

**Comment by MichaelSimons** [comment]
@FIVIL - If you follow the pattern used in our [samples Dockerfiles](https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/Dockerfile), you will gain significant gains in the local developer scenario.  If you restore as a separate layer and only copy in the csprojs and NuGet.config (if applicable), the Docker layer caching kicks in and you won't incur the costs of restoring each time you build unless your csproj changes.  

I am surprised by your earlier comment in regards to the containerized build taking longer after deleting your local package cache.  That makes me think you were coping packages into your container.  I would recommend using a .dockerignore file to exclude copying things like the local obj and bin directory into your Docker image.

Another option that can help CI/CD pipelines is a Docker BuildKit feature that is still in experimental mode.  The [RUN --mount=type=cache](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#run---mounttypecache) syntax was designed so that you can setup things like a NuGet package cache that can be used within your Docker builds.

**Comment by FIVIL** [comment]
@MichaelSimons I see, Thanks

**Comment by Ninja4Code** [comment]
I experienced this issue in Docker on a Windows 2019 Container Host. It was taking over 10 minutes to do a restore that would take about 5 seconds on my own machine. I found out that the MsMgEng.exe (Defender) process was scanning the dockerd.exe (Docker daemon). CPU usage was 98%.

To isolate the issue, run task manager while you're doing a very slow docker build. If it's Defender Real-Time scanning you will see the CPU usage through the roof on the dockerd.exe process. Defender is basically choking the Docker build!

I'm pretty sure it was just the Docker daemon but I also added docker.exe and gitlab-runner.exe on the Processor Exclusion List. The magic of process exclusion is that you don't have to exclude any folders, it will automatically refrain from scanning any folders that the process is dealing with.

And 13-minute restores are a thing of the past! That fixed it. You don't need any special params, conditions or flags on your dotnet restore.
