### ISSUE TITLE
I keep getting 1.0.0-preview* version on my latest & 1.1.0-sdk-msbuild docker installs

### ISSUE THREAD

**Issue by nozer** [dotnet/dotnet-docker#174]
I installed `microsoft/dotnet:latest` and `microsoft/dotnet:1.1.0-sdk-msbuild` docker images. 
When I run and log into both to issue `> dotnet --version` command, I always get the 1.0.0-preview* as versions 

```
x-MacBook-Pro:x y$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
dnlatest               latest              f93408b6e9ee        7 seconds ago       608.5 MB
dn110sdk               latest              03d99767bdd8        5 minutes ago       838.2 MB
microsoft/aspnetcore   1.1.0               1648fdee7eae        14 hours ago        268.1 MB
microsoft/dotnet       latest              d585ea68b366        14 hours ago        608.5 MB
microsoft/dotnet       1.1.0-sdk-msbuild   45c391ebcc0d        14 hours ago        838.2 MB

x-MacBook-Pro:x y$ docker run -it dnlatest
root@26a1fd09ec04:/myapp# dotnet --version
1.0.0-preview2-1-003177
root@26a1fd09ec04:/myapp# exit
exit

x-MacBook-Pro:x y$ docker run -it dn110sdk
root@3937bc580650:/myapp# dotnet --version
1.0.0-preview3-004056
root@3937bc580650:/myapp# 
```

How can I install the dotnet docker image where its dotnet version will be 1.1.0?

**Comment by MichaelSimons** [comment]
The Docker image version number is intended to align with the version of the runtime the image contains.   The version number you are seeing when you do `dotnet --version` is the tooling (CLI) version, not the runtime version.  The version of the tooling does not currently align with the runtime.  This is something we are working on correcting.  The `1.1.0-sdk-msbuild` image, is the image you should be using to build projects that target the 1.1.0 runtime.  You can see which runtime/shared framework is installed by looking in the `/usr/share/dotnet/shared/Microsoft.NETCore.App` folder.  The `1.1.0-sdk-msbuild` image actually contains two versions of the tooling 1.1.0 and 1.0.1.  The 1.0.1 is there because it is required by the tooling.  Again this is a point in time issue that we are working on resolving.

**Comment by nozer** [comment]
Thank you for the great explanation!
