### ISSUE TITLE
PhantomJS support

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/dotnet-docker#188]
Hi, 

I would like to use aspnetcore-build for my build process but I need PhantomJS to run my angular2 tests.

When I run npm install inside the container it fails with the following exception: "bzip2: Cannot exec: No such file or directory"

Please either add bzip2 or phantomjs to the container.

**Comment by MichaelSimons** [comment]
@SebastianStehle - Is there a reason you can't add bzip2 or phantomjs to your own image? Are you doing that now and this issue is more to make something like this work out-of-the-box for others?

We have been holding the bar high for what is added to the base images.  What is added should be things that are widely used by the image users.  The SDK images are large already, if we don't maintain this bar, the size will become unwieldy and the usefulness will diminish.

**Comment by SebastianStehle** [comment]
To be hones, when I added the issue, I was not aware that it is so easy. I created my own image now. Attached is my docker file.

But I think (or hope) that this is a very common use case.

[Dockerfile.txt](https://github.com/dotnet/dotnet-docker/files/739750/Dockerfile.txt)

**Comment by MichaelSimons** [comment]
@SebastianStehle, Glad to hear you have a solution.  Docker does make things like this nice and easy 😄 

We will continue to monitor the incoming requests on what to include in the base images.  When there is a consensus on a particular component we will update the base images.  Closing issue at point in time.
