### ISSUE TITLE
NuGet credential docs should include Windows instructions or use x-plat PS scripts

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#1895]
A user reached out to me that they got confused by the following line @ https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md#using-the-azure-artifact-credential-provider

``` Dockerfile
RUN curl -L https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | bash
```

They were using a Windows Server Core image. Can we use [this script](https://github.com/Microsoft/artifacts-credprovider#installation-on-windows)? Does it work cross-platform?

We should also discuss (again) if the NuGet credential provider should be included in the .NET SDK images.

**Comment by MichaelSimons** [comment]
One specific piece in the [NuGet guideance](https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md) that is difficult to translate to work in Windows containers is the following:

```
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS \
    "{\"endpointCredentials\": [{\"endpoint\":\"https://fabrikam.pkgs.visualstudio.com/_packaging/MyGreatFeed/nuget/v3/index.json\", \"username\":\"docker\", \"password\":\"${FEED_ACCESSTOKEN}\"}]}"
```

Getting the json quotes escaped correctly is not trivial and also differs depending on which SHELL is used (e.g. pwsh vs cmd).

**Comment by richlander** [comment]
This topic has come up a few times recently. I think we should create some scripts and Dockerfiles that demonstrate using the Azure Credential Provider more directly.

**Comment by mthalman** [comment]
> This topic has come up a few times recently. I think we should create some scripts and Dockerfiles that demonstrate using the Azure Credential Provider more directly.

Do you have specific ideas on that?  There's not much about the cred provider that is used "directly".  It's just matter of installing it and running a restore which the Dockerfile sample demonstrates.  And I'm not sure what a script would do other than build the Dockerfile, which there is also an example of in that it demonstrates how to pass the access token.

We're limited in providing a functional sample because that would require exposing a feed and its creds.

So I'm open to any thoughts on what you'd like to see.
