### ISSUE TITLE
DotNet Core SDK image vulnerability issue

### ISSUE THREAD

**Issue by wildchildyn** [dotnet/dotnet-docker#2069]
## Steps to reproduce the issue
DotNet Core SDK dockerfile installed powershell_version=7.0.1 which is an vulnerable version. 
Vulnerability name: PowerShell Denial of Service Vulnerability

## Expected behavior
PowerShell Core version should be >= 7.0.2

## Actual behavior
PowerShell 7.0.1 is installed

## Additional information (e.g. issue happens only occasionally)
This is an urgent issue. Please help fix it ASAP. Thanks!

**Comment by mthalman** [comment]
The SDK is not currently vulnerable with this issue even with 7.0.1 installed.  That's because the underlying vulnerability is in .NET Core, not PowerShell.  But because PowerShell is installed in the SDK image which has the version of .NET Core that contains the fix for this vulnerability, then there's no issue.

I assume you saw the PowerShell vulnerability announcement here: https://github.com/PowerShell/Announcements/issues/20.  From there, you'll see that it references this [CVE](https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-1108), which links to this announcement: https://github.com/dotnet/announcements/issues/156.  In that announcement, it states the issue is fixed in .NET Core SDK versions 2.1.807 and 3.1.301 which are the versions that are currently installed in the 2.1 and 3.1 SDK Docker images.

Also note that when logging security issues, be sure to follow the [security policy](https://github.com/dotnet/dotnet-docker/security/policy).

**Comment by wildchildyn** [comment]
Hi mthalman,

Our team use DotNet Core SDK as our base image. The image cannot pass S360 scan. The reason is that S360 finds PowerShell version 7.0.1 was installed in the container. As a vulnerable version, this version PowerShell shouldn't appear on the node. So DotNet Core SDK should install higher version of PowerShell.

**Comment by mthalman** [comment]
I understand the predicament.  Scanning purely based on the version number is insufficient in this case for identifying that a vulnerability exists, leading to the false positive.

The SDK images in our [nightly](https://hub.docker.com/_/microsoft-dotnet-core-nightly-sdk/) images currently have the updated 7.0.2 version.  Those updates will roll out to our [official]((https://hub.docker.com/_/microsoft-dotnet-core-sdk/) images next Tuesday as part of our regular update schedule.
