### ISSUE TITLE
Running dotnet core blazor server-side application with signalR hub doesn't allow for connections to hub when run via docker

### ISSUE THREAD

**Issue by RyanTheShaw** [dotnet/dotnet-docker#2129]
## Steps to reproduce the issue
1. Pull down the codebase found [at this repo](https://github.com/RyanTheShaw/SignalRBlazorTest)
2. Attempt to run the project with the docker definition. You'll notice that when hitting the index page, you will get an error `IOException: The response ended prematurely.`
3. Remove the comment from line#44 in Index.razer, and comment out the line#45.
4. Then run this project via IIS express and notice that there is no issue connecting to the signalR hub.

## Expected behavior
I expect to be able to execute the `await _hubConnection.StartAsync();` call in Index.razer line#55 without seeing the above exception.

## Actual behavior
When attempting to do so, you see the exception called out in the repo steps.

## Additional information (e.g. issue happens only occasionally)
This was a quick project I threw together to isolate the problem, but as you can see it works without issue when run via IIS express. I wonder if there is something I'm missing, or if this is truly an issue with docker. Extensive researching for this error hasn't found me any answers. :(

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 26
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.945GiB
 Name: docker-desktop
 ID: PMC7:WLAJ:FCBF:2K3B:7QGG:CSTU:HNT2:UZBP:OILO:5DK5:FXLR:BBTB
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 69
  Goroutines: 78
  System Time: 2020-07-28T19:58:07.381352565Z
  EventsListeners: 5
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mthalman** [comment]
@davidfowl - Are you aware of any usage of SignalR that has a seamless solution between operating inside or outside a Docker container?

**Comment by RyanTheShaw** [comment]
@mthalman @davidfowl Please let me know if there is any additional information I can provide on the issue. This issue has become a fairly major blocker on my separate web app which is already fairly far along with handling infrastructure via containers. :(

**Comment by mthalman** [comment]
The problem is the HTTPS redirection in `Startup.Configure`: https://github.com/RyanTheShaw/SignalRBlazorTest/blob/16a3289858be96aedb5d63d1fa6e5cd41dd3f073/SignalRBlazorTest/Startup.cs#L49.  Because of that, it's causing any request to the [HTTP port](https://github.com/RyanTheShaw/SignalRBlazorTest/blob/16a3289858be96aedb5d63d1fa6e5cd41dd3f073/SignalRBlazorTest/Pages/Index.razor#L45) to be redirected to the HTTPS port and that results in problems because things are misconfigured.

If you were to comment out the `app.UseHttpsRedirection` line and change the `WithUrl` line to target the host.docker.internal HTTP port 32775 instead of the HTTPS port 32774, or better yet just use localhost port 80, then things would work.

In order to have HTTPS redirection enabled, everything will need to be consistently using the HTTPS port and a certificate configured for the container to use.

This is perhaps a better question for [Stack Overflow](https://stackoverflow.com) where the audience and expertise is wider.  This is not an issue with the .NET Docker images themselves but rather an application configuration issue.

**Comment by MichaelSimons** [comment]
Closing per @mthalman's investigation.  Feel free to continue the conversation.
