### ISSUE TITLE
Stop building/testing the full repo during PR validation.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2161]
Currently the full set of Dockerfiles are built and tested whenever a src, test, eng, or manifest file is changed in the repo.  Most often this is not necessary and is therefore wasting a fair amount of compute.  This is more prevalent in the _nightly_ branch than the _master_ branch.  For example when an auto-update PR is made to pull in the most recent product versions, the Dockerfiles for the product versions that are in-service are unaffected and do not need to be built/tested.

A simple change could be made to include version triggers and only build/test the Dockerfiles for the affected version.  This approach is similar to what is used in the [dotnet/dotnet-buildtools-prereqs-docker](https://github.com/dotnet/dotnet-buildtools-prereqs-docker) repo today.  The difference is the buildtools repo triggers on the OS variant.

The downside to this approach is a separate build definition must exist for each of the product versions in support.  This adds small amount of maintenance overhead but the savings in compute overshadows this maintenance cost.

**Comment by mthalman** [comment]
A solution for this, when combined with a solution for https://github.com/dotnet/docker-tools/issues/186, would lead to decreased visibility into the correctness of Dockerfiles that do not get updated in nightly.  Since the packages that get installed by the Dockerfiles are versioned regularly, it's useful to run builds on those Dockerfiles regularly to ensure things are still working with those new packages.  In the nightly branch, it's really only 5.0 that is currently changing.  That means builds for 2.1 and 3.1 wouldn't really be happening.  But let's say a distro that is only supported by one of those .NET Core versions has a package version updated that leads to incompatibility, such as updating the libicu version.  We won't know about that incompatibility until the next time we attempt to build that Dockerfile which probably won't happen until a servicing release, which is not when we want to find out about such things.  This problem can be resolved by https://github.com/dotnet/dotnet-docker/issues/1455.

**Comment by MichaelSimons** [comment]
The point @mthalman mentions is valid and tracked with the issue he mentioned.  Catching a change in a package during PR validation is really a side effect which would be best caught via an intentional test validation whenever a package change is detected.

**Comment by mthalman** [comment]
Because of the runtime-deps dependency between 3.1 and 5.0, it ends up being very messy to implement this (https://github.com/dotnet/dotnet-docker/pull/2328).  It ends up not providing as much value as originally thought.
