### ISSUE TITLE
CVE-2019-15847 in runtime-deps:X.X-alpine3.11

### ISSUE THREAD

**Issue by burtininkai** [dotnet/dotnet-docker#2181]
Howdy,

Could You please upgrade gcc to version 9.3.0-r0 to remove CVE-2019-15847. This issue was solved a year ago.

Thx.

**Comment by mthalman** [comment]
Yes, that issue was solved a year but wasn't updated in the Alpine package feed until just 6 days ago: https://git.alpinelinux.org/aports/commit/?h=3.11-stable&id=998910db5afb89b3f84a6c9237f4c02c164fc1c5.

Automating a rebuild to handle situations like this is something that https://github.com/dotnet/dotnet-docker/issues/1455 would handle.

**Comment by mthalman** [comment]
All Alpine-based images have been rebuilt and now have version 9.3.0-r0 of libgcc.

**Comment by burtininkai** [comment]
Thank You!
