### ISSUE TITLE
VS Windows Container tools docker images 1903 not compatible with hosted agents on Azure Devops

### ISSUE THREAD

**Issue by frosadev** [dotnet/dotnet-docker#2194]
Hi Folks,

We're not able to build docker images if using the suggested windows images from VS container tools on hosted agents (Azure Devops).

![image](https://user-images.githubusercontent.com/26621392/91546655-b434c480-e91a-11ea-8060-cb59db468caf.png)

## Expected behavior

Match the versions from dotnet templates with the hosted agents on Azure Devops.

## Actual behavior
![image](https://user-images.githubusercontent.com/26621392/91546916-1ee60000-e91b-11ea-8efe-b8d960013ac7.png)

![image](https://user-images.githubusercontent.com/26621392/91546815-f6f69c80-e91a-11ea-85ad-efa85c31c311.png)

**Comment by mthalman** [comment]
This is expected due to [Windows container version compatibility](https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/version-compatibility) requirements.  Windows Server, version 1903 is a higher version than Windows Server 2019 and so the agent is not capable of building such a Dockerfile.  You'd either need to change your tags to 5.0-nanoserver-1809, which maps to Windows Server 2019, or define your own custom agent that uses Windows Server, version 1903 instead of using a hosted agent.
