### ISSUE TITLE
How to handle base image CVE

### ISSUE THREAD

**Issue by som-nitjsr** [dotnet/dotnet-docker#2232]
## Steps to reproduce the issue
i am using mcr.microsoft.com/dotnet/core/aspnet:3.1.8-buster-slim AS base
and black duck tool is reporting CVE-2019-8457 and BDSA-2017-0611 in **Berkeley DB5.3.28**
how should i handle this even we are not using **Berkeley DB5.3.28**

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by mthalman** [comment]
Can you provide any link for more info about BDSA-2017-0611?  I can find nothing about it.  Berkeley DB5 corresponds to the 
[db5.3 package](https://security-tracker.debian.org/tracker/source-package/db5.3).  That package gets installed as an indirect dependency of curl.  The latest stable version of of the db5.3 package available for buster is 5.3.28+dfsg1-0.5 which is the version that is already installed in the image.  It's possible that the flagged vulnerability that the scanner is finding is fixed in version 5.3.28+dfsg1-0.6 of the package but that is currently in the testing repository, not stable.

Having [CVE-2019-8457](https://security-tracker.debian.org/tracker/CVE-2019-8457) show up is odd because that is for the sqlite3 package and that package is not installed in this image.  False positive?

**Comment by som-nitjsr** [comment]
for CVE-2019-8457 you are correct. thanks. i have checked the base image and sql lite is not there.

for BDSA-2017-0611 

Technical Description
The /etc/shadow file in POSIX environments contains hashes of user passwords and is the counterpart of the world-readable /etc/passwd file. Under normal circumstances only the root user should be able to read it.

Berkeley DB reads its DB_CONFIG file from the current working directory. As this library is used in a number of commands which run in the context of the root user, this can pose an extremely serious security risk. By symlinking /etc/shadow to DB_CONFIG in the current directory and then invoking an arbitrary instance of a certain command, the first line of /etc/shadow will be returned in the error message. In most cases, this will contain the hash of the root user's password. From here, depending on the strength of the password, it is only a matter of time before the password is cracked and the system fully compromised.

https://seclists.org/oss-sec/2017/q2/452


Can you also please help us in below CVE
https://nvd.nist.gov/vuln/detail/CVE-2019-18276
https://nvd.nist.gov/vuln/detail/CVE-2019-5443
https://nvd.nist.gov/vuln/detail/CVE-2019-12290
https://nvd.nist.gov/vuln/detail/CVE-2020-13776

Note: all these are in mcr.microsoft.com/dotnet/core/aspnet:3.1.8-buster-slim AS base

**Comment by MichaelSimons** [comment]
@som-nitjsr, please see the _Security Updates and Vulnerability Scanning_ section of this [blog](https://devblogs.microsoft.com/dotnet/staying-up-to-date-with-net-container-images/) to learn how we keep the .NET images up-to-date when security fixes are available.  We do offer `Alpine` based images as a more secure offering over Debian and Ubuntu.  If you have a concern about vulnerabilities, this may be an attractive alternative to consider.

**Comment by som-nitjsr** [comment]
Hi we have discussed alpine vs debian and gone with debian. can you please share any link for comparison/ recommendation.
also i wans not able to access the full scan report it is just going to anchore.io https://anchore.io/image/dockerhub/8626492fecd368469e92258dfcafe055f636cb9cbc321a5865a98a0a6c99b8dd?repo=library%2Fdebian&tag=latest#security

**Comment by mthalman** [comment]
BDSA-2017-0611 seems to correspond to [CVE-2017-10140](https://security-tracker.debian.org/tracker/CVE-2017-10140) which is fixed in version 5.3.28+dfsg1-0.5 of db5.3.  That's the version that's installed in the image.  So another false positive?

> Can you also please help us in below CVE
> https://nvd.nist.gov/vuln/detail/CVE-2019-18276
> https://nvd.nist.gov/vuln/detail/CVE-2019-5443
> https://nvd.nist.gov/vuln/detail/CVE-2019-12290
> https://nvd.nist.gov/vuln/detail/CVE-2020-13776

I would invite you to research these on your own by using https://security-tracker.debian.org.  If you're able to identify any out-of-date packages in the .NET Docker images that have security implications, please let us know.

**Comment by MichaelSimons** [comment]
>also i wans not able to access the full scan report it is just going to anchore.io https://anchore.io/image/dockerhub/8626492fecd368469e92258dfcafe055f636cb9cbc321a5865a98a0a6c99b8dd?repo=library%2Fdebian&tag=latest#security

Unfortunately since the blog was originally posted, Anchore requires a subscription to view image vulnerabilities.  You will have to scan the images with your preferred security scanner to see the results.

**Comment by som-nitjsr** [comment]
Thanks I am closing this issue and will investigate other issues.

**Comment by som-nitjsr** [comment]
Hi @mthalman  is there any way i can remove Curl from base image as we are not using it. which in turn will remove   dependency libdb5.3 (Berkeley db)
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.8-buster-slim AS base
RUN apt-get –-purge remove libdb5.3 -y

**Comment by mthalman** [comment]
The command to do this would be `apt-get purge --auto-remove curl` which would remove curl and all of it's unused dependencies.  However, it appears there are more packages that have a dependency on libdb5.3 that appear to be essential.  You can do reverse dependency lookup on a package by running `apt-cache rdepends libdb5.3`.

My suggestion would be to revisit the decision to choose Debian over Alpine.

**Comment by MichaelSimons** [comment]
@som-nitjsr - FYI, curl has been removed in the 5.0 images which [RC 1 was recently released](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1/).

**Comment by MichaelSimons** [comment]
Closing per Matt's earlier guidance on how to remove curl.
