### ISSUE TITLE
Improve running .NET in containers as a non-root user

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2249]
# Improve running .NET in containers as a non-root user
We see an increasing number of requests from users seeking guidance on running containers as non-root users.  A primary driver for running as non-root is related to reducing vulnerabilities.  [This issue](https://github.com/dotnet/dotnet-docker/issues/1757#issuecomment-604497687) discusses why we don't define a non-root user within the .NET images.  This issues explores and tracks ways we can enhance .NET to better support running in containers as a non-root user.

## .NET Docker
* [Include documentation and samples that demonstrate USER best practices](https://github.com/dotnet/dotnet-docker/issues/1772)

## Runtime
* [Kestrel does not support running as non-root on Alpine](https://github.com/dotnet/aspnetcore/issues/4699)

**Comment by ChrisHanna** [comment]
Hi @MichaelSimons, we are running into this exact issue where the base image is getting flagged during vulnerability scans. I understand, our reasoning behind not defining a non-root user for our base images. However, in our case developers cannot add the base image to an enterprise container registry without first passing the scan. So they are required to get an exception, and state that they will define the non root user in their docker file. The other option is for them to create their own image from the netcore 3.1 base image, and define a non root user before putting it in their container registry. Is it a possibility to provide both a root 3.1 base image and a non-root base image or provide a little more direction in our documentation.

**Comment by biltongza** [comment]
+1 to this, mounting a volume causes things to be written to as root which can cause some headaches if you aren't expecting it.

**Comment by IvanJosipovic** [comment]
There was some guidance posted recently here, https://techcommunity.microsoft.com/t5/azure-developer-community-blog/hardening-an-asp-net-container-running-on-kubernetes/ba-p/2542224

**Comment by olljanat** [comment]
IMO it would make sense to default to non-root user starting from some new version release (e.g. .NET 6.0 or .NET 7.0) and highlight that on release notes.

**Comment by olljanat** [comment]
FYI. I started working on this on PR #3139

**Comment by jcotton42** [comment]
On the Visual Studio side user secrets are mounted into /root, which makes development painful.

**Comment by olljanat** [comment]
> FYI. I started working on this on PR #3139

FYI. As that one didn't reached consensus so I'm shared examples how to handle this with different container orchestration tools in https://github.com/dotnet/dotnet-docker/issues/1772#issuecomment-1196483685

**Comment by mthalman** [comment]
There's also this proposal which is aimed at improving the onboarding experience for using a non-root user: https://github.com/dotnet/designs/pull/271

**Comment by mthalman** [comment]
Here's the PR for adding support for the new `ASPNETCORE_HTTP_PORTS` environment variable: https://github.com/dotnet/aspnetcore/pull/44194.

**Comment by EklipZgit** [comment]
Pretty related, coming to the conclusion of https://github.com/dotnet/runtime/issues/81456 
The default Azure AppService behavior for running linux containers maps the /home directory to azure storage, sets permissions to 777 and ignores any attempts to change permissions.
The dotnet runtime will not write certs to the dotnet ca store unless it and only it has read permissions on the directory.
The moment you run as a non-root user with default home in the /home directory on an Azure AppService with default settings, you can't cache certificate chains. Feels like something that ought to be called out in some documentation, somewhere. Not sure if relevant to this specific ticket since it is a clash between the runtime and Azure AppServices, but the impact to the non-root scenario seems like something this crowd of people might be interested in.
