### ISSUE TITLE
Git missing in Windows-based SDK image (available on Linux)

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/dotnet-docker#2338]
[git is installed on the Linux-based SDK images](https://github.com/dotnet/dotnet-docker/blob/master/eng/dockerfile-templates/sdk/5.0/Dockerfile.linux#L18), but is missing from the Windows-based SDK images.

It would be great if git would be available on the Windows-based SDK images, too.

**Comment by MichaelSimons** [comment]
Thanks for opening this issue.  This is something we will investigate for 6.0.

**Comment by johnjaylward** [comment]
I'd really like to see this as well. We have some applications that still require us to use "Framework" and at the moment not having git available in the Windows images is limiting our migration to use docker for these applications

**Comment by mthalman** [comment]
We should revisit this for .NET 7. It would provide better parity between the two OS types and also better enable the ability to define a cross-platform Dockerfile.

**Comment by mthalman** [comment]
### Open Questions

1. How to avoid manually updating the version number when retrieving the download URL version. I'd like to not have to manually maintain a version that the URL is pinned to; it's just extra overhead for us to deal with. But just getting the latest version could lead to breaking changes if the latest ends up crossing a major version boundary. This could be compensated with logic that gets the latest version of a specific major version.

1. Where should git be downloaded from? Git is available for download from GitHub. But it's also available through winget. At this point in time, winget isn't supported on Windows Server so that's not an option right now. But it could be in the future if it were to ever be supported there.

1. Git is likely supported on Windows Server Core but what about Nano Server. Need to do testing on both of those.

**Comment by richlander** [comment]
In general, I think this is a good idea. As you suggest Matt, it's a question about how to do it in a good way.
