### ISSUE TITLE
Consider removing the .NET (Preview) product family repo from Docker Hub.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2361]
There is a _Product Family_ repo for [.NET](https://hub.docker.com/_/microsoft-dotnet) as well at [.NET (Preview)](https://hub.docker.com/_/microsoft-dotnet-nightly).  The primary purpose of the _Product Family_ repos is to provide a landing page of sorts with information about the group of repos.  The contents are mostly identical to the .NET _Product Family_ repo.  The primary difference is the _Featured Repos_ section.  I question the value of having this repo given the redundant information.  I believe that fewer repos would provide a better UX.

**Comment by richlander** [comment]
Good question. Bias to simplicity.

**Comment by mthalman** [comment]
This will need to be a multi-step process.

- [ ] Manually update https://github.com/microsoft/mcrdocs/blob/master/teams/dotnet/nightly/README.md with a message to redirect to https://hub.docker.com/_/microsoft-dotnet
- [ ] Ensure https://hub.docker.com/_/microsoft-dotnet-nightly shows the updated content from the previous step
- [ ] Remove the dotnet/nightly product family [registration](https://github.com/microsoft/mcr/blob/2538383ab6957dcc277d4caca7ec20c59afc647f/teams/dotnet/nightly/dotnet-nightly.yml#L8-L21).

At this point Docker Hub has been updated and future builds can update the readme that gets published to mcrdocs without affecting Docker Hub.

- [ ] Make a request to Docker Hub via MCR to have the https://hub.docker.com/_/microsoft-dotnet-nightly page deleted.
- [ ] Update readme templates so that any reference to https://hub.docker.com/_/microsoft-dotnet-nightly instead points to https://hub.docker.com/_/microsoft-dotnet.
