### ISSUE TITLE
icu-libs in Alpine SDK but not runtime

### ISSUE THREAD

**Issue by brettrowberry** [dotnet/dotnet-docker#2365]
### Describe the Problem
In .NET 5 Alpine SDK images, icu-libs are included - but not in the runtime images. 

### Describe the Solution
Include or remove icu-libs from both images. 

### Additional Context
See https://andrewlock.net/dotnet-core-docker-and-cultures-solving-culture-issues-porting-a-net-core-app-from-windows-to-linux/

**Comment by richlander** [comment]
Good issue. We need to make a final decision on https://github.com/dotnet/dotnet-docker/issues/1877 within the 6.0 release. That will help us resolve this issue.

**Comment by brettrowberry** [comment]
Thanks @richlander! I want the leanest .NET 5 (and beyond) images I can get. I want to minmize local dev setup time and CI build time.

**Comment by richlander** [comment]
I agree with both of those sentiments! We'll see what we can do.

**Comment by mthalman** [comment]
I think the key here is with the setting of `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` to `false`. We can control that in the SDK by not setting that way. We can also avoid explicitly installing icu, but we can't necessarily guarantee that it won't exist due to a dependency on some other package that we do install. For example, in the sdk we install `git`. Today it doesn't have a dependency on icu but we can't necessarily guarantee it won't some day.

**Comment by lbussell** [comment]
Alpine images with ICU libs are now available with the `-extra` image variant: https://github.com/dotnet/dotnet-docker/blob/main/documentation/image-variants.md#extra-net-80
