### ISSUE TITLE
aspnet:5.0 image Unable to load shared library 'libdl.so'

### ISSUE THREAD

**Issue by atlemagnussen** [dotnet/dotnet-docker#2397]
### Describe the Bug

I have a project that I upgraded to NET5 and changed my dockerfile to use the official image `mcr.microsoft.com/dotnet/aspnet:5.0`

Then I get this error: 
"Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory"

This was not the case for 3.1

The app also runs fine on my Debian and Ubuntu machines, so that is why I figure it must be something with the docker image

### Steps to Reproduce

For me it's inside the package Google.Cloud.SecretManager.V1 the error occours.
So install this package in a web app and run the code `var client = SecretManagerServiceClient.Create();`
will provoke it

### Other Information

I found a workaround, by installing libc6-dev in the dockerfile:
`RUN apt-get install -y libc6-dev` 

### Output of `docker version`

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Output of `docker info`

Client:
 Debug Mode: false

Server:
 Containers: 24
  Running: 0
  Paused: 0
  Stopped: 24
 Images: 263
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.84-microsoft-standard
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 12.27GiB
 Name: ATLE-WORKTOP
 ID: QIKX:IUYU:42XM:74AF:5QJ6:QTWO:QB32:2JB4:KXYK:6IO7:RTIT:4CRG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by MichaelSimons** [comment]
@atlemagnussen, Can you clarify something for me.  Does this scenario work for you with the mcr.microsoft.com/dotnet/aspnet:3.1 image?

**Comment by atlemagnussen** [comment]
@MichaelSimons Yes it works with the mcr.microsoft.com/dotnet/aspnet:3.1 image

**Comment by MichaelSimons** [comment]
The only differences in the packages between 3.1 and 5.0 are related to the [removal of curl](https://github.com/dotnet/dotnet-docker/issues/2379).  As a result, the following packages were removed from 5.0.

```
curl/now 7.64.0-4+deb10u1 amd64
libcurl4/now 7.64.0-4+deb10u1 amd64
libldap-2.4-2/now 2.4.47+dfsg-3+deb10u3 amd64
libldap-common/now 2.4.47+dfsg-3+deb10u3 all
libnghttp2-14/now 1.36.0-2+deb10u1 amd64
libpsl5/now 0.20.2-2 amd64
librtmp1/now 2.4+20151223.gitfa8646d.1-2 amd64
libsasl2-2/now 2.1.27+dfsg-1+deb10u1 amd64
libsasl2-modules-db/now 2.1.27+dfsg-1+deb10u1 amd64
libssh2-1/now 1.8.0-2.1 amd64
```

`libc6-dev` is not part of the 3.1 image nor is libdl.so so I am not sure I can explain why this scenario works in 3.1 and not in 5.0.  Is it possible Google.Cloud.SecretManager.V1 has a fallback and uses other dependencies if present?  One easy way to see if this is indeed related to the removal of curl would be to simply add `curl` instead of `libc6-dev` and see if your scenario works.

**Comment by atlemagnussen** [comment]
@MichaelSimons adding curl did not help, but thanks. It does not necessarily sound like your problem.

I can provide feedback to Google and see if they might look into it

**Comment by MichaelSimons** [comment]
One other question is if your dependency on the Google.Cloud.SecretManager.V1 package is pinned to a particular version.  I did happen to notice a new version was recently released.  Perhaps something changed in their implementation or an upstream dependency.  In any case, this doesn't appear to be a problem specific to the .NET Docker images.  If you find this is specific to the .NET Docker images please let us know.

**Comment by dheerajjain11** [comment]
Has any solution found for it? I faced exactly the same issues

**Comment by atlemagnussen** [comment]
> Has any solution found for it? I faced exactly the same issues

@dheerajjain11 not except the workaround I mention in the initial post :(

**Comment by sunliusi** [comment]
same problem

**Comment by tmds** [comment]
Can you share a stack trace from the `System.DllNotFoundException`? It may show what depends on `libdl.so`.

**Comment by BillyGeoThink2020** [comment]
I have Been having this Problem always

Tom Deseyn ***@***.***> schrieb am Mi., 31. März 2021, 11:25:

**Comment by engdanielcarneiro** [comment]
Same issue here:

`Jun  8 00:32:36 ip-172-31-4-124 web: System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg)
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.UnmanagedLibrary.PlatformSpecificLoadLibrary(String libraryPath, String& errorMsg)
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.NativeExtension..ctor()
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.NativeExtension.Get()
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Internal.NativeMethods.Get()
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.GrpcEnvironment..ctor()
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.GrpcEnvironment.AddRef()
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
Jun  8 00:32:36 ip-172-31-4-124 web: at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
Jun  8 00:32:36 ip-172-31-4-124 web: at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, IEnumerable`1 channelOptions, ChannelCredentials credentials)
Jun  8 00:32:36 ip-172-31-4-124 web: at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, IEnumerable`1 channelOptions)
Jun  8 00:32:36 ip-172-31-4-124 web: at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint)
Jun  8 00:32:36 ip-172-31-4-124 web: at Google.Cloud.Firestore.V1.FirestoreClient.Create(ServiceEndpoint endpoint, FirestoreSettings settings)
Jun  8 00:32:36 ip-172-31-4-124 web: at Google.Cloud.Firestore.FirestoreDb.Create(String projectId, FirestoreClient client)
Jun  8 00:32:36 ip-172-31-4-124 web: at BankingAPIs_API.Services.FirestoreDbService..ctor(IConfiguration configuration) in D:\projects\yes-we-code\repo\open-api\backend\FYA-API\Services\FirestoreDbService.cs:line 21
Jun  8 00:32:36 ip-172-31-4-124 web: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Jun  8 00:32:36 ip-172-31-4-124 web: at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
Jun  8 00:32:36 ip-172-31-4-124 web: at lambda_method15(Closure , IServiceProvider , Object[] )
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun  8 00:32:36 ip-172-31-4-124 web: at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Jun  8 00:32:36 ip-172-31-4-124 web: --- End of stack trace from previous location ---`

**Comment by joe-wroe-dft** [comment]
Has anyone found a solution to this?

Interestingly the original posts workaround seems to be working for us when running the Docker image locally, but it fails when running the Docker image on GCP infrastructure.
