### ISSUE TITLE
ASPNETCORE_URLS Reset to empty?

### ISSUE THREAD

**Issue by saber-wang** [dotnet/dotnet-docker#2406]
![CDB45EAF-D86A-4dfc-AF52-24B8F1A943AF](https://user-images.githubusercontent.com/45062099/99868126-bf864c00-2bfa-11eb-8b7f-86aabd788a71.png)

image: mcr.microsoft.com/dotnet/nightly/aspnet:5.0-alpine

**Comment by MichaelSimons** [comment]
> image: mcr.microsoft.com/dotnet/nightly/aspnet:5.0-alpine

@saber-wang, This doesn't look like the `aspnet:5.0-alpine` image. Are you certain that you have pulled the latest image?  Are you certain you are not looking at the `sdk` image? The `sdk` image purposely clears the `ASPNETCORE_URLS` value set in the base runtime layer. You can see this by comparing the output of `docker history --no-trunc mcr.microsoft.com/dotnet/nightly/aspnet:5.0-alpine` vs `docker history --no-trunc mcr.microsoft.com/dotnet/nightly/sdk:5.0-alpine`

As a side note, I see you are using the _nightly_ images.  I wanted to make sure this was intentional.  The _nightly_ images contain pre-release versions of the product.  See https://hub.docker.com/_/microsoft-dotnet-core for the latest officially released images.

**Comment by saber-wang** [comment]
@MichaelSimons Sorry, it's my problem
