### ISSUE TITLE
Describe policy on publishing images based on "latest" bits

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2571]
This should describe the criteria that we require in order for publishing to proceed as well as the criteria that we do not check.  The aim is to provide more transparency into the process and our philosophy of using the latest version of bits, particularly within the Linux ecosystem.

**Comment by begerard** [comment]
Currently the "latest" tag only provide full windows/debian image, and do not offer the other variants, like nano/alpine.

Can we have new tags like lastest-alpine, latest-nanoserver-1809 ...?

**Comment by mthalman** [comment]
> Currently the "latest" tag only provide full windows/debian image, and do not offer the other variants, like nano/alpine.
> 
> Can we have new tags like lastest-alpine, latest-nanoserver-1809 ...?

Please create a separate issue with that request. This issue is referring to "latest" bits in the general sense of the term; it is not referring to the `latest` tag.

**Comment by begerard** [comment]
Done, thanks Matt.

**Comment by lbussell** [comment]
[Triage] Closing since this issue needs more details.

Documentation about the contents of our images can be found in the [Image update policy](https://github.com/dotnet/dotnet-docker?tab=readme-ov-file#image-update-policy), [Container vulnerability workflow](https://github.com/dotnet/dotnet-docker/blob/main/documentation/vulnerability-reporting.md), and the contents of the Dockerfiles themselves.
