### ISSUE TITLE
Feature request : build a microsoft/dotnet:2.0-sdk with mono image

### ISSUE THREAD

**Issue by StefH** [dotnet/dotnet-docker#271]
I want to use the latest **microsoft/dotnet:2.0-sdk** image to build an application which targets `netcoreapp2.0` and `net452`. But this doesn't work because net 4.5.2 cannot be compiled in a **microsoft/dotnet:2.0-sdk** image.

So my request is : can you please create a microsoft/dotnet:2.0-sdk with mono installed image ?

**Comment by kendrahavens** [comment]
Just to clarify, we don't see publishing and supporting images that include mono as part of our area of focus at this time.

On a side note: what OS are you targeting for this? If you are just interested in running .NET 4.5.2 with the .NET Core sdk you could definitely use the [.NET Framework](https://hub.docker.com/r/microsoft/dotnet-framework/) image and layer .NET Core on it rather than dealing with mono in order to target Linux.

**Comment by StefH** [comment]
OK. Clear.

Actually I want to use a docker image to build my project, which supports a lot of frameworks like:\
* net 2.0
* net 3.5
* net 4.0
* net 4.5
* net 4.5.1 / net 4.5.2
* net 4.6 / net 4.6.1 / net 4.6.2
* net 4.7
* dotnetcore 1.0 / dotnetcore 1.1 / dotnetcore 2.0

Is this possible using a existing **nano** image? Or should I create my own ?

**Comment by kendrahavens** [comment]
There are two different versions of windows containers. There is Nano Server and Windowsservercore. Nano does not work with the full .NET Framework, but Windowsservercore is quite a bit bigger and can run the full .NET Framework. I'd suggest using the Windowsservercore base image for your purposes. We publish .NET Core on Nano images because it is the smallest version of windows containers. The [.NET Framework uses the Windowsservercore](https://hub.docker.com/r/microsoft/dotnet-framework/) base image. You'll have to add steps in your Dockerfile to install .NET Core on the .NET Framework image as well, but that shouldn't be too challenging.

I'll close this since this feature request is not in our scope, but feel free to ask more questions. Your scenario sounds quite interesting! :)
