### ISSUE TITLE
Please provide an image for ASP.NET Core with IIS and ANCM installed

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#2814]
I was talking to a customer today. They wanted an image with with ASP.NET Core ready for IIS hosting. They tried to install the ASP.NET Core 3.1 hosting bundle (MSI) installed and that failed.

Proposal:

- For 6.0, enable IIS and install ANCM for the ServerCore image.
- For 3.1, ensure that IIS, ANCM and .NET Core 3.1 can be installed on a Windows Server Core 2019 image. If not, fix whatever the problem is and share the working Dockerfile.

**Comment by MichaelSimons** [comment]
[Triage] Assigning to @richlander, to investigate the 3.1 issue.

**Comment by richlander** [comment]
Filed an issue https://github.com/dotnet/aspnetcore/issues/32955.

**Comment by mthalman** [comment]
Added a sample Dockerfile that demonstrates installing IIS and ANCM: https://github.com/dotnet/dotnet-docker/pull/2908. This is all we're planning to do for now.  Providing this in the aspnet image is undesirable due to the size concerns with IIS (see https://github.com/dotnet/dotnet-docker/pull/2908#issuecomment-871740780).
