### ISSUE TITLE
dotnet application execution issues

### ISSUE THREAD

**Issue by DeepakTI** [dotnet/dotnet-docker#284]
I have developed a sample dotnet web application using microsoft/dotnet:latest image.
After development i tried running it on supported dotnet run time as below:
microsoft/dotnet:2.0.0-runtime-jessie
microsoft/dotnet :1.1.2-runtime
microsoft/dotnet :1.0.5-runtime

The sample dotnet application executed successfully only on microsoft/dotnet :1.1.2-runtime out of three images above but failed on rest of two with below (same) error during execution:

root@76738b24a62b:/app# dotnet app.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.

Check application dependencies and target a framework version installed at:
/
Alternatively, install the framework version '1.1.2'.
root@76738b24a62b:/app# exit
So, does it means that an application developed in SDK 1.1.2 has to run on only corresponding run time ? and can't be run on any run time version above or below?

-Thanks!

**Comment by MichaelSimons** [comment]
@DeepakTI - It is by design that you can't take an app compiled against 1.1.* and run it on 1.0.* or 2.*  You should be able to run it on a new 1.1.* however.  [This](https://gist.github.com/schellap/c2260ee9755fce1d78a564183be4609d#shared-framework-selection) is the best description of the behavior I could find.  I logged an issue to provide clarity in the [.NET Core application deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/) documentation.

**Comment by MichaelSimons** [comment]
There is a related [Docs issue](https://github.com/dotnet/docs/issues/2880) to clarify the documentation on this topic.
