### ISSUE TITLE
Grpc.Tools: Cannot run protoc in alpine based dotnet SDK 

### ISSUE THREAD

**Issue by lamLeX** [dotnet/dotnet-docker#2842]
### Describe the Bug

I encountered the same issue like this https://github.com/grpc/grpc/issues/18338 when trying to build a grpc project with `dotnet/sdk:5.0-alpine`

### Other Information

There is a work around reported in https://github.com/grpc/grpc/issues/18338. Can we incorporate that workaround in the base sdk alpine image instead?

**Comment by mthalman** [comment]
I did try [one of the workarounds that installed `libc6-compat`](https://github.com/grpc/grpc/issues/18338#issuecomment-472643433) but that doesn't work.  It runs into the error: `#11 1.924   Error relocating /root/.nuget/packages/grpc.tools/1.19.0/tools/linux_x64/grpc_csharp_plugin: __strftime_l: symbol not found`

The other [workaround](https://github.com/grpc/grpc/issues/18428#issuecomment-537033229) that is posted is available as a package from an untrusted source which would not be appropriate to define within the official .NET Docker images. Given that, it looks like the recommendation from the grpc repo is to use this workaround.

I do see that there is another, possible duplicate, [issue](https://github.com/grpc/grpc/issues/24188) open on this matter that could be commented on.

Closing since we won't be installing packages from untrusted sources.
