### ISSUE TITLE
Please add a SxS SDK image

### ISSUE THREAD

**Issue by NCarlsonMSFT** [dotnet/dotnet-docker#2945]
### Describe the Problem
I have a .NET 5 project that uses NuGets which require .NET Core 3.1 and cannot be built using the available SDK images.

### Describe the Solution
Please add a supported SDK image that includes all in-support SDKs which would allow building the broadest range of projects/solutions.

### Additional Context
The default template for Azure Functions targeting .NET 5 runs into this issue.

**Comment by MichaelSimons** [comment]
[Triage] @mthalman, can you please investigate and report back your findings/recommendation?

**Comment by mthalman** [comment]
I've dug into this to determine what's causing the dependency on 3.1.  Attempting to build an Azure Functions project in a 5.0 SDK container causes the following build error:

```
#15 12.39   WorkerExtensions -> /tmp/3ebcnwh1.olw/buildout/Microsoft.Azure.Functions.Worker.Extensions.dll
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - The following frameworks were found: [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :       5.0.7 at [/usr/share/dotnet/shared/Microsoft.NETCore.App] [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : You can resolve the problem by installing the specified framework and/or SDK. [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The specified framework can be found at: [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64 [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
#15 12.44 /root/.nuget/packages/microsoft.net.sdk.functions/3.0.11/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : Metadata generation failed. [/tmp/3ebcnwh1.olw/WorkerExtensions.csproj]
```

What I see happening is that the Azure Functions build logic generates a temporary `WorkerExtensions.csproj` project.  This is part of the https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/3.0.11 implementation. It then runs a `GenerateFunctions` MSBuild task on that project which launches a pre-built framework-dependent .NET app called `Microsoft.NET.Sdk.Functions.Generator.dll`, located in the `tools/netcoreapp3.1` directory of the aforementioned NuGet package; it just executes `dotnet Microsoft.NET.Sdk.Functions.Generator.dll`. This fails with the above error because the assembly is built on .NET Core 3.1: https://github.com/Azure/azure-functions-vs-build-sdk/blob/b507604e7150ead37a4d7ad11ed4ff9566a22200/src/Microsoft.NET.Sdk.Functions.Generator/Microsoft.NET.Sdk.Functions.Generator.csproj#L5.

Arguably, Azure Functions should be distributing self-contained apps in the tools folder of their NuGet package, not framework-dependent since there is no guarantee of what .NET version will be installed in the running environment.

**Comment by mthalman** [comment]
Rather than a self-contained deployment, which would require RID-specific deployed assets, the guidance is to use the major version roll forward option  so that a 3.1 app can run in 5.0:

```xml
<RollForward>LatestMajor</RollForward>
```

Given that Azure Functions can modify their NuGet package to operate in this environment and there are no other compelling scenarios requiring an SDK image that combines 3.1 and 5.0, there are no plans to provide multiples .NET versions in an SDK image.

**Comment by mthalman** [comment]
I've logged https://github.com/Azure/Azure-Functions/issues/1983 for Azure Functions to address this issue.
