### ISSUE TITLE
PowerShell Vulnerability Reported in SDK Docker Image Scans

### ISSUE THREAD

**Issue by dzrhythm** [dotnet/dotnet-docker#3115]
### Describe the Bug

Image scans like Qualys in Azure Security Center report vulnerabilities due to outdated PowerShell Core versions on the dotnet/sdk tags 3.1 and 5.0.

Related CVEs:
CVE-2021-26423
CVE-2021-34485

### Steps to Reproduce

Perform an image scan.

### Other Information

Remediation, update to PowerShell 7.0.7 and 7.1.4 respectively.

**Comment by mthalman** [comment]
This is a false positive.  The CVEs listed are actually for .NET Core.  PowerShell Core is being incorrectly flagged for them because, by default, PowerShell Core ships with a version of .NET Core. But that version of .NET Core is not actually being included in the container image.

As an example, PowerShell Core 7.0.6 (the version that's being flagged as vulnerable) ships with .NET Core 3.1.17.  That version of .NET Core does have the vulnerability. However, the version of .NET Core that is actually installed in the latest 3.1 container images is 3.1.18 which does not have the vulnerability. The way in which PowerShell Core is installed into the container image omits the version of .NET Core that comes with it by default. So we're installing PowerShell Core 7.0.7, for example, but leaving out .NET Core 3.1.17 and instead explicitly installing .NET Core 3.1.18.  This all applies to 5.0 as well.

**Comment by MichaelSimons** [comment]
[Triage] Closing per Matt's previous response.  PowerShell will also be updated in the Sept patch cycle.

**Comment by dzrhythm** [comment]
Thanks for the explanations.
