### ISSUE TITLE
mcr.microsoft.com/dotnet/sdk:6.0 is Git does not support SSH

### ISSUE THREAD

**Issue by whuanle** [dotnet/dotnet-docker#3299]
mcr.microsoft.com/dotnet/sdk:3.1
```bash
root@f9b94b753cac:/tmp# git clone git@github.com:whuanle/kubernetes_book.git
Cloning into 'kubernetes_book'...
The authenticity of host 'github.com (20.205.243.166)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no)? 

```
 mcr.microsoft.com/dotnet/sdk:6.0
```bash
root@44b57914244d:/tmp# git clone -b fat git@github.com:whuanle/kubernetes_book.git  
Cloning into 'kubernetes_book'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

**Comment by whuanle** [comment]
Git works if i install ssh-client.

**Comment by mthalman** [comment]
This is due to the [removal of buildpack-deps from sdk images](https://github.com/dotnet/dotnet-docker/issues/2376) which occurred in .NET 5. It works with the `mcr.microsoft.com/dotnet/sdk:3.1` image because it is based on `buildpack-deps:buster-scm` which has `ssh-client` installed. But the dependency on the buildpack-deps base image does not exist in `mcr.microsoft.com/dotnet/sdk:5.0` and `mcr.microsoft.com/dotnet/sdk:6.0` so you're not getting that package "for free" anymore.

Instead, you'll need to explicitly install it by adding the following to your Dockerfile:

```Dockerfile
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ssh-client \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by mthalman** [comment]
Triage: Closing per the guidance provided in https://github.com/dotnet/dotnet-docker/issues/3299#issuecomment-976813012.
