### ISSUE TITLE
ASP.NET Core Docker image for buster-slim-arm32v7

### ISSUE THREAD

**Issue by mu88** [dotnet/dotnet-docker#3334]
### Describe the Problem

I've been using Docker on my Raspberry Pi. The Raspi's OS is Debian 10 aka "Buster". Now I wanted to upgrade my applications to .NET 6, but I didn't find any successor of `5.0.12-buster-slim-arm32v7` like `6.0.0-buster-slim-arm32v7` or something else - only `6.0.0-bullseye-slim-arm32v7`, which would require me to upgrade my Raspi.

### Describe the Solution

Provide .NET 6 Docker images for  `6.x.y-buster-slim-arm32v7`.

**Comment by mthalman** [comment]
[Triage] Since you're using Linux containers, there isn't a requirement that the version of the host OS match the version of the container. Are you running into specific issues getting a Debian 11 (Bullseye) container working on your Raspberry Pi? This should be possible, with the caveat of this [known issue related to libseccomp and Docker](https://github.com/dotnet/dotnet-docker/issues/3351).

**Comment by mu88** [comment]
Honestly I didn't know that - I will give it a try over the holidays.

Do you want me to close the issue and reopen it in case I'm running into issues?
