### ISSUE TITLE
sac2016 points to 10.0.14393.1884 build ...

### ISSUE THREAD

**Issue by martencassel** [dotnet/dotnet-docker#342]
## Steps to reproduce the issue

Either i'm confused about LTSC vs SAC regarding nanoserver vs windowservercore
 or you probably have a incorrectly tagged the microsoft/nanoserver:sac2016 and therefore all your dotnet based images of this. 

The microsoft/nanoserver:sac2016 tag points to an image with OSVersion: '10.0.14393.1884'

Is build 10.0.14393.1884 part of the Semi Annual Channel Release ? 
Isnt the first SAC release, Windows Server 1709 and whatever build that is? 
I'm very confused.

## Expected behavior

docker pull microsoft/dotnet:1.0.8-runtime-nanoserver-sac2016
Error response from daemon: manifest for microsoft/dotnet:1.0.8-runtime-nanoserver-sac2016 not found

docker pull microsoft/dotnet:1.0.8-runtime-nanoserver-ltsc2016
(Image get pulled)

C:\build>docker inspect --format='{{.OsVersion}}' microsoft/dotnet:1.0.8-runtime-nanoserver-ltsc2016
'10.0.14393.1884'

## Actual behavior

docker pull microsoft/dotnet:1.0.8-runtime-nanoserver-sac2016
(Image get pulled)

C:\build>docker inspect --format='{{.OsVersion}}' microsoft/nanoserver:sac2016
'10.0.14393.1884'

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
@martencassel, I empathize with you on this.  It is difficult to get an understanding of the Windows versioning.

> Is build 10.0.14393.1884 part of the Semi Annual Channel Release ?
yes

> Isnt the first SAC release, Windows Server 1709 and whatever build that is?
1709 is the second release in the sac channel.  @enderb-ms - It seems like two things could help this situation.  First, the microsoft/nanoserver 1709 images should have a `sac` prefixed tag.  Second, the [note](https://docs.microsoft.com/en-us/windows-server/get-started/semi-annual-channel-overview) here stating 1709 is the first release should be updated accordingly.

> docker pull microsoft/dotnet:1.0.8-runtime-nanoserver-ltsc2016
This version of Nano Server is not from the ltsc channel which is why the tag doesn't exist.  There isn't an ltsc Nano Server version.  See https://hub.docker.com/r/microsoft/nanoserver/

**Comment by MichaelSimons** [comment]
To summarize, microsoft/dotnet uses a suffix on its Windows images that aligns with the Windows base image tags - e.g. nanoserver-sac2016 and nanoserver-1709.  Any questions on the [Windows tagging](https://hub.docker.com/r/microsoft/nanoserver/) or suggestions on clarifying the [documentation ](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/semi-annual-channel-overview.md) should be directed towards the Windows Docker images.
