### ISSUE TITLE
Fix or update Apache.Avro nuget packages

### ISSUE THREAD

**Issue by valentynbulakh** [dotnet/dotnet-docker#3560]
Hi
We are using azure-functions to build docker image,
After build we do Aqua Scanner to check Vulnerabilities.
The latest image 4.1.3 hat 4 Vulnerabilities related to Apache.Avro.
https://nvd.nist.gov/vuln/detail/CVE-2021-43045

This issue if fixed in Apache.Avro version 1.11.0.
In azure-functions image version is 1.10.2.

Can you update image to use latest Apache.Avro version or how we can do this?
Tried to update like this:
RUN python3 -m pip install avro
RUN dotnet add package Apache.Avro --version 1.11.0
RUN dotnet tool install --global Apache.Avro.Tools --version 1.11.0

But has no luck, it's updating it, but Aqua Scanner still shows that old version is present.
Maybe image has some library or dependency that should be updated.

We already using custom image
as base image we are using mcr.microsoft.com/dotnet/aspnet:3.1-alpine3.14
and as build mcr.microsoft.com/dotnet/core/sdk:3.1-buster

Both images are have the similar issues.

**Comment by mthalman** [comment]
> Can you update image to use latest Apache.Avro version or how we can do this?

Neither of the two images you mention (`mcr.microsoft.com/dotnet/aspnet:3.1-alpine3.14`, `mcr.microsoft.com/dotnet/core/sdk:3.1-buster`) contain any Apache Avro NuGet packages. This vulnerability is unrelated to the container images produced by this repo. I've followed up at https://github.com/Azure/azure-functions-docker/issues/612#issuecomment-1067078536 because it does show up in the Azure Functions image though.
