### ISSUE TITLE
mcr.microsoft.com/dotnet/aspnet:6.0-jammy `signatures couldn't be verified because the public key is not available`

### ISSUE THREAD

**Issue by khteh** [dotnet/dotnet-docker#3767]
### Describe the Bug

Using `mcr.microsoft.com/dotnet/aspnet:6.0-jammy` to build docker image for ASP.Net 6 results in `signatures couldn't be verified because the public key is not available` error.

Repo: https://github.com/khteh/AspNetCoreApiStarter
Error: https://app.circleci.com/pipelines/github/khteh/AspNetCoreApiStarter/278/workflows/8ba4d75a-e8c6-499d-907e-ac545105f638/jobs/289/parallel-runs/0/steps/0-111

**Comment by mthalman** [comment]
I'm unable to repro this. This was likely a temporary issue in the configuration of Ubuntu. Keep in mind that the command you're running isn't dependent on .NET at all. In the future, please verify commands like this on the base image tag: `ubuntu:jammy`. That would help pinpoint where the issue is so that you can log an issue in the appropriate repo (.NET, Ubuntu, etc).
