### ISSUE TITLE
Distroless image binds to privileged port 

### ISSUE THREAD

**Issue by rwkarg** [dotnet/dotnet-docker#3796]
https://github.com/dotnet/dotnet-docker/blob/4adcfb2ba73d019049c4767b603d72ae299b5c8a/src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile#L50

The container uses the non-root user `USER app` but that user doesn't have permission to bind to port 80. 
See https://github.com/dotnet/dotnet-docker/issues/3448

A container using a non-root user should default to using non-privileged ports
ex. http:5000 and https:5001
OR
http:8080 and https:8443

**Comment by mthalman** [comment]
I've been researching this to try to figure out why this works locally on Docker Desktop but fails in our build machines (and even at one time it did work in our build machines).

Turns out there was a change to the defaults in https://github.com/moby/moby/pull/41030 that allowed privileged ports to be used starting in Docker Engine version 20.3.0. That would explain why it's working for me locally. For the behavior of the build agents, here's the timeline:

1. It was working on internal and public builds.
2. We migrated to the NetCore1ESPool-Internal pool for the internal builds. At that time, it started failing in those builds. Docker version on those machines was 19.03.8 at that time. So those machines would not have had the new default change in https://github.com/moby/moby/pull/41030.
3. The machines in the NetCore1ESPool-Internal pool had their Docker version upgraded to 20.10.x. The tests began working again after that.
4. Later, the issue cropped up again, this time affecting public builds as well, unrelated to the NetCore1ESPool-Internal pool.

My hypothesis for #4 is that the Azure kernel was updated to disallow this capability from being set. That's why it suddenly affected both internal and public builds. Even today, if I attempt to add `--sysctl net.ipv4.ip_unprivileged_port_start=0` to the `docker run` command, it won't fix the issue when running on an Azure-hosted machine.

Given that the use of privileged ports is dependent on the configuration of the host (and seemingly not even possible in Azure), I think our best course of action is to change the default port for container images configured with a non-root user. After surveying to see what others have done, my preference would be to use port 8080.

I've also verified that changing the port to 8080 causes the tests to pass (related to https://github.com/dotnet/dotnet-docker/issues/3448).

**Comment by craigktreasure** [comment]
I hit this some time ago and it appears to be a difference in behavior between dockerd and containerd. See https://github.com/dotnet/aspnetcore/issues/4699 and https://github.com/containerd/containerd/issues/2516.

**Comment by mthalman** [comment]
@craigktreasure - What is your preference for how to resolve this? I assume you overrode `ASPNETCORE_URLS`?

**Comment by richlander** [comment]
Is this issue distroless-specific?

**Comment by mthalman** [comment]
> Is this issue distroless-specific?

Yes, because that's the only container type we use a non-root user by default.

**Comment by richlander** [comment]
I grasp that. I makes sense to ask whether we should adjust the default to work for both user types.

**Comment by mthalman** [comment]
[Triage]

Our preference is to maintain as little friction as possible for the default root user scenario. In that case, the container types that use a root user would continue to use port 80. Any attempt to change that default would be a breaking change and could easily break a lot of `docker run` scenarios. With the distroless/non-root user container type, the default port would be changed to a non-privileged port (e.g. 8080).

We should still cater to users that are defining their own root user. In that case, having documentation to describe how to configure the Dockerfile and `docker run` command would be helpful. This would also extend into the space of setting up Azure services where those commands may be more hidden from the user and require other knobs to turn that should be called out to help guide the user to success when working with non-root users in their .NET containers.

**Comment by craigktreasure** [comment]
Sounds great. Some documentation to go along with it would be much appreciated.
