### ISSUE TITLE
Tags latest, 6.0 and 6.0.8 apply to nanoserver 1809 only

### ISSUE THREAD

**Issue by mloskot** [dotnet/dotnet-docker#3993]
### Describe the Bug

These tags at https://hub.docker.com/_/microsoft-dotnet-aspnet listed for nanoserver 20H2 are wrong:

![image](https://user-images.githubusercontent.com/80741/184433506-53d56c2d-1e71-44e4-a44f-abab7f551a79.png)

These tags apply only to nanoserver 1809

![image](https://user-images.githubusercontent.com/80741/184433698-d14ca475-8d93-4046-8dc4-5a4a1ba87554.png)

### Steps to Reproduce

N/A

### Other Information

N/A

### Output of `docker version`

N/A

### Output of `docker info`

N/A

**Comment by mthalman** [comment]
The `6.0` and `6.0.8` tags are examples of manifest list tags (also known as shared tags, multi-arch tags, and multi-platform tags). They are dynamic in what image they retrieve based on the host that is pulling them.

Based on the host that you pull the tag from, Docker will automatically resolve it to the appropriate image that matches the platform of the host. So if you're pulling from an Arm64 Linux host, you'll get an Arm64 Linux image. For Windows, it's a bit difference since Windows has [version compatibility requirements](https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/version-compatibility). If you're pulling the image from a Windows Server 10.0.17763.3287 machine, you'll get the image associated with that OS version.

You can inspect these tags to understand how they work:

```
> docker manifest inspect mcr.microsoft.com/dotnet/aspnet:6.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1371,
         "digest": "sha256:4884c144e4ab879cddde0daa67949dc0feb856d92be7e043b31eff398d132fb0",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1371,
         "digest": "sha256:ac753b1563dd4e5a6b3b53b54f04afa1996a60bcb35cc21a7581c91dcfe6d38d",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1371,
         "digest": "sha256:e76bfba638fb35fe89af5f4db1064900183eb05252a0d3c16063ac97dfc7b8c5",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2174,
         "digest": "sha256:e1bbfcd95a232140d55ecec2e30bffb0d8d09d16e6e22fccc8b468620710662e",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.3287"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2174,
         "digest": "sha256:1f05b2a9446b5775665b5bbeb0e878a5393c23e6c541cc3d3af3d39e20a9152d",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19042.1889"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2174,
         "digest": "sha256:d22efaae6281e47c8206f8263cb3cc065e2a9d59701c7517e4a669b591d11a23",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.20348.887"
         }
      }
   ]
}
```

You can see that the tag is associated with multiple images, all represented as separate manifest entries. Each entry has an OS, architecture, and version (for Windows). This is how Docker resolves the tag to an image.

So in response to this issue, the tags are correctly defined since a `6.0` tag applies to multiple Windows versions.

**Comment by mloskot** [comment]
> They are dynamic in what image they retrieve based on the host that is pulling them

I see. I had no idea. Thank you for the explanation. 
It could be put somewhere in the description, I guess.

**Comment by richlander** [comment]
There isn't a way for us to easy describe that information within the Docker Hub UI. Manifest tags are also a complex topic to explain and we rarely get asked about it.

Related: https://github.com/dotnet/announcements/issues/14
