### ISSUE TITLE
Start aspnet rc2 with docker container on localhost:5000 not working

### ISSUE THREAD

**Issue by Adribb** [dotnet/dotnet-docker#41]
Hey, 
i try to start a web Application aspnet rc2 with docker container, i write in my DockerfIle
`FROM microsoft/dotnet:onbuild`

and i run the following commands : 
```
$ docker build -t my-dotnet-app .
$ docker run -it --rm --name my-running-app my-dotnet-app
```
The docker container work perfectly and i see : 
Project dotnetapp (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling dotnetapp for .NETCoreApp,Version=v1.0
```

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:07.5362630
 

info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Production
Content root path: /dotnetapp
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

But i try to acces on http://localhost:5000 and the url not working: 
> ERR_CONNECTION_REFUSED

Thanks.

**Comment by MichaelSimons** [comment]
@Adribb - I believe the problem is that your application is listening on `http://localhost`.  I think the docker port forwarding functionality defaults to `0.0.0.0`.  This means the `http://localhost:5000` request you are making is actually coming in as `http://0.0.0.0:5000` to your container.  To fix this you can call `.UseUrls("http://0.0.0.0:XXX")` within your Startup Main method on the WebHostBuilder.

```
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseUrls("http://0.0.0.0:5000")
                .Build();
```

**Comment by Adribb** [comment]
Your solution works perfectly
Thank you !
