### ISSUE TITLE
docker Image for .netcore 2.0

### ISSUE THREAD

**Issue by AmrElshaer** [dotnet/dotnet-docker#4173]

**Comment by mthalman** [comment]
@AmrElshaer - In order to have the best response, it is helpful to put more detail into logged issues. This issue only contains a title, which is little to go on.

I'm assuming you're wanting images for .NET Core 2.0. That version of .NET Core has been out of support for 4 years and we no longer provide images for it. This is the PR that removed the 2.0 Dockerfiles from the repo at that time: https://github.com/dotnet/dotnet-docker/pull/712. You may find that helpful to use as a reference if you'd like to build your own images based on that version.
