### ISSUE TITLE
Critical vulnerability in zlib in dotnet-alpine image (CVE-2022-37434)

### ISSUE THREAD

**Issue by asterix75** [dotnet/dotnet-docker#4230]
There is a rather new vulnerability in the zlib that also affects the dotnet alpine image.
It is recorded as CVE-2022-37434 and appears in zlib including version 1.2.12.

The problem seems fixed in zlib 1.2.13.
Please update your base images accordingly (also see zlib.net homepage).

How to reproduce:
Can base image with security scanner
or
Read out version of zlib in docker image and compare with vulnerability databases.

**Comment by mthalman** [comment]
This appears to be a false positive by whichever scanning tool you are using.

From Alpine's own [security page for this CVE](https://security.alpinelinux.org/vuln/CVE-2022-37434), it states that the vulnerability is fixed in version 1.2.12-r3 (note the revision number suffix). This is the same version that's currently installed in the .NET Alpine images:

```
> docker run --rm mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.16 apk list zlib
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
zlib-1.2.12-r3 x86_64 {zlib} (Zlib) [installed]
```

This is also the latest version available for that package as can be seen from [Alpine's zlib package page](https://pkgs.alpinelinux.org/packages?name=zlib&branch=v3.16&repo=&arch=&maintainer=):


![image](https://user-images.githubusercontent.com/15789599/204825959-ab69df27-7a63-46a5-92dd-696448263e9a.png)
