### ISSUE TITLE
The shell for `app` should be the same as `root`

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#4467]
The two shells are different. I don't believe that's intentional. We're only wanting to differentiate the users on permissions.

```bash
# docker run --rm mcr.microsoft.com/dotnet/aspnet:8.0-preview cat /etc/passwd | grep /bin/
root:x:0:0:root:/root:/bin/bash
sync:x:4:65534:sync:/bin:/bin/sync
app:x:101:101::/home/app:/bin/false
```

**Comment by mthalman** [comment]
[Triage]
This configuration occurred because the implementation of creating the user is shared with the implementation for our distroless Dockerfiles. In the distroless scenario, it does make sense to not have the shell set since there is none. It was just an oversight to not update the shell definition when definining the non-root user for the distroful scenario.

**Comment by lbussell** [comment]
https://github.com/dotnet/dotnet-docker/pull/4477 makes it so that non-distroless images leave the shell unchanged when creating the non-root user.
