### ISSUE TITLE
Any plans about mono-based ASP.NET Core image?

### ISSUE THREAD

**Issue by s-tarasov** [dotnet/dotnet-docker#45]

**Comment by vassilvk** [comment]
The default Docker images as of RC1 targeted `dnx451` and were mono-based. Many people developed around those images mainly because it will take a long time for libraries out there to catch up and be ported to CoreCLR.

I second @s-tarasov's question -- I think it is important to know what the road-map looks like as it relates to `dnx451` support on Linux.

**Comment by MichaelSimons** [comment]
Moved to aspnet-docker repo - https://github.com/aspnet/aspnet-docker/issues/153.  Closing this issue.
