### ISSUE TITLE
Unexpected preview tagging scheme values for the new 8.0 preview images

### ISSUE THREAD

**Issue by baronfel** [dotnet/dotnet-docker#4524]
### Describe the Bug

The new preview images have a tagging scheme that's out of alignment with [the proposal](https://github.com/dotnet/dotnet-docker/issues/4117) - instead of `8.0-preview.N`, images with the `8.0.0-preview.N` format are visible on mcr.microsoft.com. I'd like to request retags to fix the version numbers - this mismatch impacts tag inference for the SDK container build tooling.

### Other Information

Screenshot of dotnet/aspnet tags matching preview.2:

![image](https://user-images.githubusercontent.com/573979/228651143-20970a0e-b2a4-4242-aa10-e41bdc605cd0.png)

**Comment by mthalman** [comment]
[Triage]
This was an inaccuracy in the original [proposal](https://github.com/dotnet/dotnet-docker/issues/4117). It doesn't really provide any value to have both `8.0-preview.N` and `8.0.0-preview.N` tags because they will always be synonymous. Normally, a two-part version number like `8.0` would be a floating tag that would be updated with each servicing release. But in the context of previews, that doesn't happen. The three-part version number will always be `8.0.0` for each preview release. So `8.0` and `8.0.0` are always equivalent for each preview release.

For that reason, we won't be publishing any `8.0-preview.N` tags. We'll get the original proposal updated to reflect this.
