### ISSUE TITLE
Vulnerable image mcr.microsoft.com/dotnet/sdk:6.0

### ISSUE THREAD

**Issue by oronboni** [dotnet/dotnet-docker#4568]
### Describe the Bug

Base on Qualys scanning the image: mcr.microsoft.com/dotnet/sdk:6.0 has the following CVEs

http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-0820
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-34716
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-8292
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-24112

### Other Information
![image](https://user-images.githubusercontent.com/18048655/232329256-2faa1d0d-39d8-434d-b4a9-af9c5b3454fd.png)

**Comment by mjprager** [comment]
DOTNET team - it's possible these are false positives? A fellow security peer offered that "It appears this is because the path where SDK is installed gets misclassified and the scanner assumes it’s looking at an application. The scanner proceeds to read *.deps.json files in this path and treats them as application metadata about referenced assemblies. This approach doesn’t work if it’s an SDK. Even if the deps.json files referenced a vulnerable package, no vulnerable assemblies are shipped with the SDK."

It would be good to have this affirmed if true, or the vulns must be fixed if not.

**Comment by mthalman** [comment]
Duplicate of https://github.com/dotnet/sdk/issues/30659
