### ISSUE TITLE
Improve the output of the VerifyDotnetFolderContents test

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4843]
Currently, the output of the [VerifyDotnetFolderContents test](https://github.com/dotnet/dotnet-docker/blob/e025c2591fa197bf1e8ca1d8d07b0a34c4fba4a7/tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs#L135-L136) looks something like this:
```
ACTUAL FILES:
<very long list of every single file and sha in the dotnet folder>

EXPECTED FILES:
<another very long list of every expected file and sha in the dotnet folder>
```

This requires the user to download the test output and check which files are extra/missing/different using an external tool. We should instead output a diff of the two directories when the test fails.

**Comment by ellahathaway** [comment]
I assigned myself since I have some extra time between tasks to take this on.

I've reviewed Logan's PR with the changes, so I'll work on re-implementing some of those changes in a new PR. The changes in Logan's PR tackle two issues, but given the unpredictability of my time with the other work I'm being assigned, I plan on tackling just the portion of his changes that relate to this issue first.
