### ISSUE TITLE
Missing (nightly) Jammy Chiseled Images for .NET 8.0 RC2

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#4884]
```bash
> docker pull mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-rc.2-jammy-chiseled
docker: Error response from daemon: manifest for mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-rc.2-jammy-chiseled
not found: manifest unknown: manifest tagged by "8.0.0-rc.2-jammy-chiseled" is not found.

> docker pull mcr.microsoft.com/dotnet/nightly/aspnet:8.0-jammy-chiseled
sha256:33aa741c0d014abc1c10bdd3be53df6157ab5497fae1fa41b1d02cf248439032

> docker run --rm mcr.microsoft.com/dotnet/nightly/aspnet:8.0-jammy-chiseled --list-runtimes
Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

It appears that jammy chiseled images were not built in [build #2267111](https://dev.azure.com/dnceng/internal/_build/results?buildId=2267111&view=results) [internal link]. It's unclear why, as they were updated in the PR: https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet-docker/commit/17a7751414cedfd91de034384db4ecc10732bd58?path=/src/aspnet/8.0/jammy-chiseled/amd64/Dockerfile. If I had to guess it would be due to build matrix generation issues that have recently been plaguing jammy chiseled in particular. Related: https://github.com/dotnet/docker-tools/issues/1178

This could be related to why dotnet monitor images are failing to test in https://github.com/dotnet/dotnet-docker/pull/4875, as they depend on the ASP.NET images which are now being referenced as 8.0.0-rc.2.

**Comment by mthalman** [comment]
This is kind of in the gray area of expected behavior.

The build we should be first looking at is the one which was automatically triggered when the Dockerfiles were changed from RC1 to RC2: https://dev.azure.com/dnceng/internal/_build/results?buildId=2266952&view=results (internal link). That one failed from a transient error. It should have been retried to complete that build.

The [link you referred to](https://dev.azure.com/dnceng/internal/_build/results?buildId=2267111&view=results) is for an auto-queued build to rebuild images whose base images have changed. That was run later. The reason it was queued at all is not because base images had changed. Instead, it couldn't find any image info entries for those Dockerfiles that it ended up running a build for. It couldn't find entries because the tags of those images had been changed (rc1 to rc2) so it couldn't find a match. When it can't find any image info for a Dockerfile, it ensures that that Dockerfile gets rebuilt. Keep in mind that the primary purpose of this pipeline is to check for base image updates. So it's only looking for Dockerfiles whose base image can be queried to see if it changed. In the case of Chiseled Dockerfiles, there is no base image since they're based on `scratch`. So it ignored those Dockerfiles during its processing. That's why they weren't included.

I don't think there's anything that needs to be fixed in the logic as a result of this. As long as we ensure that triggered builds are completed, then we're good.

**Comment by lbussell** [comment]
Hmm, I see what went wrong now. I'll make sure that any failing triggered builds get completed in the future before merging more PRs. Seeing as `mcr.microsoft.com/dotnet/nightly/runtime:8.0.0-rc.2-jammy-chiseled` this can be closed now.
