### ISSUE TITLE
RUN update-ca-certificates fails with 8.0-alpine images

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/dotnet-docker#4997]
### Describe the Bug

`RUN update-ca-certificates` fails with erro 127 on ALPINE .Net 8 images. Works fine on 7.0 alpine and "latest" .net 8

### Steps to Reproduce

Get any cert.

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine

COPY yourCertFile.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

### Other Information

error message is: `ERROR: failed to solve: process "/bin/sh -c update-ca-certificates" did not complete successfully: exit code: 127`

### Output of `docker version`

Azure Pipeline

**Comment by lbussell** [comment]
For .NET 8.0 Alpine images, the `ca-certificates` package was removed in lieu of the `ca-certificates-base` package that comes from the base Alpine image. `ca-certificates-bundle` contains all of the same certificates as `ca-certificates` so that you can still make HTTPS requests, but leaves out some tools (like `update-ca-certificates`) in order to save space since not every project needs them. This also brings Alpine in line with Ubuntu Chiseled images which also only contain `ca-certificates-data`.

This is documented in the [.NET 8.0 container images release announcement](https://github.com/dotnet/dotnet-docker/discussions/4995) as well as the [general .NET 8.0 breaking change documentation](https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/krb5-libs-package). Also see https://github.com/dotnet/dotnet-docker/issues/4751 and https://github.com/dotnet/dotnet-docker/pull/4773#issuecomment-1646084903 for more context.

To add `ca-certificates` in your own image, update your Dockerfile's RUN instruction to:
```
RUN apk add --upgrade --no-cache ca-certificates && update-ca-certificates
```

Or you can try using our Ubuntu or Debian images which contain `ca-certificates` by default.

**Comment by lbussell** [comment]
[Triage] Closing this issue since this is intentional and documented.
