### ISSUE TITLE
runtime:8.0-alpine image does not add ncurses-terminfo-base making it impossible for Console.ReadKey to work properly

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/dotnet-docker#5016]
Based on @tmds founding at https://github.com/dotnet/runtime/issues/64355 it turns out that our `sdk` image comes with `ncurses-terminfo-base`, while `runtime` does not. It's making it impossible for `Console.ReadKey` to work properly.

From [sdk/8.0/alpine3.18/amd64/Dockerfile](https://github.com/dotnet/dotnet-docker/blob/dbad8de557e0f943fe5103f9c165ac3300832d97/src/sdk/8.0/alpine3.18/amd64/Dockerfile#L50-L51):

```
    # Add ncurses-terminfo-base to resolve psreadline dependency
    && apk add --no-cache ncurses-terminfo-base
```

**Comment by adamsitnik** [comment]
cc @richlander

**Comment by lbussell** [comment]
[Triage] Per our [guiding principles on image contents](https://github.com/dotnet/dotnet-docker/blob/main/documentation/guiding-principles.md#image-content), the base images are intended to satisfy the most common scenarios and it's expected that in some instances you will need to add your own packages in a derived image. Since `ncurses-terminfo-base` isn't a strict dependency of the .NET Runtime, we won't explicitly install it. You can use the `apk` command you referenced from the SDK Dockerfile above in order to install it in your own image if you are creating an interactive console app with the Runtime image.

**Comment by richlander** [comment]
Is reading console input a common scenario in container images? They are not often interactive.

Here's the size difference:

- Baseline: 7.66MB
- With `ncurses-terminfo-base`: 7.79MB

That's uncompressed with Arm64.

I don't think the size is a key decision maker. It's more the scenario. As suggested, there is clearly a workaround.
