### ISSUE TITLE
Question: change Alpine RID to musl

### ISSUE THREAD

**Issue by kasper3** [dotnet/dotnet-docker#505]
In release/2.1 and master branches of CoreFX, CoreCLR and CoreSetup and [CLI's release/2.1.3xx branch], alpine-3.6-x64 is changed to musl-linux-x64.

While it would make the sense to keep the docker name having "alpine", but should we update the alpine docker builder to reflect the alpine->musl changes?

@weshaggard, @MichaelSimons

**Comment by MichaelSimons** [comment]
@kasper3 - I am not following what you are asking?  What do you mean by "update the apline docker builder"?  

The tag names should remain using the name `alpine` because that is the distro the images are based on.  I [recently updated](https://github.com/dotnet/dotnet-docker/commit/55a991a52ecff3f136fa322dd6f027841fd50817#diff-029e248e8a55af299dc7b47d8c3dfc43) the installer references within the Alpine Dockerfiles to reference the new `musl` based artifacts.  This work was done in the `[nightly](https://github.com/dotnet/dotnet-docker/tree/nightly)` branch.

**Comment by kasper3** [comment]
Great to have RC1 artifacts in nightly, I totally forgot about nightly branch :)

Thanks and cheers! 🎉
