### ISSUE TITLE
Produce Ubuntu 24.04 images (Noble Numbat)

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#5181]
The next Ubuntu LTS is practically on our doorstep.

We should do the following:

- Do nothing for .NET 6/7
- Add Noble to .NET 8
- Ship only Noble (for Ubuntu) for .NET 9

**Comment by lbussell** [comment]
[Triage] We discussed if 9.0-preview.3 images should include Noble in the main branch before it is release. Since 9.0 is already a preview, it should be acceptable to ship Noble in the main branch as a preview for what we will actually ship. We don't want to maintain Jammy support for 9.0 since it's not in our plans to ship it.

**Comment by richlander** [comment]
Sounds great!

**Comment by lbussell** [comment]
These images are now available for .NET 8: https://github.com/dotnet/dotnet-docker/discussions/5466

.NET 9 Noble images are available in the nightly repos. When Preview 4 is released, they will be available in the non-nightly repos.
