### ISSUE TITLE
createdump in chiseled runtime images

### ISSUE THREAD

**Issue by tmds** [dotnet/dotnet-docker#5183]
I took a look in the Chiseled runtime images, and found there to be two executable:
`dotnet` (needed to run the application), and also `createdump` (which enables creating coredumps of .NET applications).

Maybe it makes sense to remove the latter?

cc @mthalman @richlander

**Comment by lbussell** [comment]
I checked on this. The path is `/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.0/createdump` and it's 106K in the `mcr.microsoft.com/dotnet/runtime:8.0-jammy-chiseled` image. We'll discuss this today at triage.

**Comment by lbussell** [comment]
[Triage] @mikem8361, I noticed you commit frequently on the `createdump` code. Can you provide any background on why this tool is bundled with the Runtime instead of as some separate component? Is it called automatically?

**Comment by mikem8361** [comment]
Yes, it is exec'ed directly by the runtime if certain env vars are set when a app hits an unhandled exceptions or crashes.  It is also launched (via the diagnostics server pipe) when dotnet-dump collect is executed to capture "hang" dumps or memory usage. You can think it as part of the runtime. For single-file apps it is linked directly in.

**Comment by lbussell** [comment]
In order for Chiseled images to maintain compatibility with .NET diagnostic tools such as .NET Monitor, it seems like we need to keep `createdump` around, so I am closing this issue.

If in the future the Runtime is bundled with other unnecessary tools/data that take up too much space for non-interactive installs, we should look at how we can solve the issue from a .NET packaging perspective rather than just removing files we don't deem necessary.
