### ISSUE TITLE
Consider creating container images with ,NET diagnostic CLI tools

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/dotnet-docker#5189]
### Describe the Problem

Sometimes we need to do production debugging and need to use [.NET diagnostic tools](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/tools-overview) and it would be nice to have a container image available with these tools.

### Describe the Solution

There are images for [dotnet-monitor](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-monitor) (mcr.microsoft.com/dotnet/monitor), but it would be nice to have images for:

- [dotnet-counters](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters)
- [dotnet-dump](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump)
- [dotnet-gcdump](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-gcdump)
- [dotnet-trace](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace)
- [dotnet-stack](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-stack)
- [dotnet-symbol](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-symbol)

/cc @richlander

**Comment by akoken** [comment]
In my opinion, including these tools in base images might not be advisable due to concerns regarding security and image size, among other factors. Generally, many deployments may not require these tools. If you don't use a distroless base image, you can always install them within the container as needed.

**Comment by paulomorgado** [comment]
The idea is to create an image like **dotnet/monitor** but with the other tools.

In some environments, if desired, users could add that image instead of maintaining their own images.

**Comment by jander-msft** [comment]
@paulomorgado, can you explain a user scenario more concretely?

I ask because the .NET Monitor images provide much of the same capabilities of the tools that you have listed. It supports collecting counters, memory dumps, GC dumps, even traces, and stack traces, among other capabilities. What scenario do you have that the dotnet-monitor image is not capable of supporting?

**Comment by richlander** [comment]
Referencing some issues I found in case that's useful:

- https://github.com/dotnet/dotnet-docker/issues/1737
- https://github.com/dotnet/dotnet-docker/issues/1672
- https://github.com/dotnet/dotnet-docker/issues/5183

Another scenario might be to have a chiseled image (for size) to contain these tools as single file executables so that it would be super easy for folks to `COPY` them into their own images. The SDK tooling could do the same thing.

**Comment by paulomorgado** [comment]
@jander-msft, it's not that .NET Monitor cannot handle, it's another set of tools in the toolbelt.

**Comment by lbussell** [comment]
[Triage] @paulomorgado what is the specific scenario that .NET Monitor doesn't fulfill that you need the additional diagnostic tools for?

**Comment by paulomorgado** [comment]
Is .NET Monitor capable of all tasks mentioned by @Maoni0 in her [mem-doc](https://github.com/Maoni0/mem-doc)?

**Comment by lbussell** [comment]
[Triage] The .NET Monitor images are intended to cover diagnostic scenarios. If there's a specific task in that document that you can't do with the .NET Monitor images, please open a separate issue for it.
