### ISSUE TITLE
libdl.so: cannot open shared object file: No such file or...

### ISSUE THREAD

**Issue by scalalang2** [dotnet/dotnet-docker#5379]
### Disclaimer.
This has also been issued at `Discussions` channel #4938 

### Describe the Bug
`libdl.so cannot open shared object file`
The above error occurred when I upgraded dotnet sdk version from 7.0 to 8.0.

It's resolved once I manually link `libdl.so.2` to `libdl.so`.
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app

...

RUN ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so

...

ENTRYPOINT ["dotnet", "Application.dll"]
````

I'm reporting this as a bug because I'm not sure whether this is intended or not.

**Comment by richlander** [comment]
We made two key changes that could have contributed to this difference in behavior.

- `7.0` images use Debian 11 and `8.0` images use Debian 12.
- We updated (relatively) high-level dependencies: https://github.com/dotnet/dotnet-docker/pull/4847/files#diff-173e84769ad27ec062ab24d69093f74489ec6c130a756164e2b4df91289ddc1a

Here are the relevant `runtime-deps` Dockerfiles:

- `6.0`/`7.0`: https://github.com/dotnet/dotnet-docker/blob/6f32b916ff36e8ff8e3f22b79c0978e4a9392c59/src/runtime-deps/6.0/bullseye-slim/amd64/Dockerfile
- `8.0`: https://github.com/dotnet/dotnet-docker/blob/6f32b916ff36e8ff8e3f22b79c0978e4a9392c59/src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile

This is what I see.

```bash
rich@mazama:~$ docker run --rm mcr.microsoft.com/dotnet/runtime-deps:7.0 bash -c "find . | grep libdl"
./lib/x86_64-linux-gnu/libdl.so.2
./lib/x86_64-linux-gnu/libdl-2.31.so
rich@mazama:~$ docker run --rm mcr.microsoft.com/dotnet/runtime-deps:8.0 bash -c "find . | grep libdl"
./usr/lib/x86_64-linux-gnu/libdl.so.2
```

This leads me to believe that something else is at play. I don't see `libdl.so` in our images, symbolically linked or otherwise.

From a quick read, it seems like `dlopen` functionality moved to `libc` and that fully modern software should rely on those public exports. I assume that's what we're doing with our native dependencies.

**Comment by richlander** [comment]
This issue makes it sound like the transition to Debian 12 is relevant: https://stackoverflow.com/questions/75855053/how-to-address-crash-due-to-missing-libdl-so-on-ubuntu-22

My guess is the following:

- Some software is being compiled (as the StackOverflow page suggests) linking `libdl.so`.
- User Dockerfiles installed additional components that added this component/symlink into their container images
- Debian 12 (and other distros) made a breaking change such that `libdl.so` is no longer present (even if you install those same components as before).

That leaves two options (assuming the guess is correct):

- Users can manually create the symlink.
- Other software should be updated to no longer link `libdl.so`.

It isn't obvious what our role would be in that.

As an aside, we compile CoreCLR in containers to ensure that we have a well-defined environment: https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/linux-instructions.md.

**Comment by lbussell** [comment]
[Triage] @scalalang2 According to @jkotas in the discussion thread, it sounds like the issue is with some library you're using referencing `libdl.so` directly. Can you tell from the error message which library or package this error is coming from? If it isn't from .NET itself then it doesn't seem like this is an issue with the .NET container images.
