### ISSUE TITLE
Heredocs (<<EOF) syntax in samples doesn't work on Windows when using default Git line ending settings

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5402]
https://github.com/dotnet/dotnet-docker/blob/3e8c396639c30387237fc898d9152858b479a458/samples/releasesapi/Dockerfile.debian-cross-arm64-x64#L6-L10

1. This syntax is only used in the releasesapi samples and isn't consistent with our other samples.
2. This syntax does not work on Windows when using Git's default "checkout with CRLF, commit LF" setting.

Proposal: Remove heredocs in samples or provide a note about this in the samples README.

Workaround: Switch the file to LF line endings using your editor before building the sample.

**Comment by richlander** [comment]
I'm happy with any option. I noticed that this worked poorly on Windows when I made it was too stubborn to relent. Such surprising behavior for me.

**Comment by lbussell** [comment]
Here's the issue for that - https://github.com/moby/buildkit/issues/4282

**Comment by polarathene** [comment]
<details>
<summary>Collapsed as doesn't contribute much to the discussion</summary>

> 2\. This syntax does not work on Windows when using Git's default "checkout with CRLF, commit LF" setting.

> Workaround: Switch the file to LF line endings using your editor before building the sample.

> Another option is to specify the line ending for these files specifically with the `.gitattributes` file
> 
> However, this could blow up if a user copies this to their repo and doesn't include the gitattributes. Since this doesn't provide a ton of value, we should just remove the Heredocs.

FWIW, [`.gitattributes` has been used on projects I maintain](https://github.com/docker-mailserver/docker-mailserver/blob/94751e00c9787c5223e39bd0cd5b139a0c1f6255/.gitattributes#L23) to avoid the issue and it's been a non-problem.

That said:
- I'm probably one of the few that builds images for such projects on Windows, whereas your demographic may very much be more likely to encounter the concern.
- Copy/pasting examples (_where editors like VSCode would default to CRLF on Windows_) since there isn't as much reason to clone the repo for such, I can see why you'd want to drop the syntax (_as nice as it is_).

</details>

**Comment by lbussell** [comment]
As you mentioned, @polarathene, the primary purpose of the samples is to be easy to run and understand. A syntax that depends on a specific line ending to work is a no-go.

These have been removed from the samples with https://github.com/dotnet/dotnet-docker/pull/5882, so I'm closing the issue as complete.
