### ISSUE TITLE
Security risk in Docker image: CVE-2023-45853, CVE-2023-50387, CVE-2024-0553

### ISSUE THREAD

**Issue by danieleforberghi** [dotnet/dotnet-docker#5508]
FROM mcr.microsoft.com/dotnet/sdk:6.0
FROM mcr.microsoft.com/dotnet/aspnet:6.0

FROM mcr.microsoft.com/dotnet/sdk:8.0
FROM mcr.microsoft.com/dotnet/aspnet:8.0

[CVE-2023-45853 ](https://security-tracker.debian.org/tracker/CVE-2023-45853)	 Critical	9.8	No	Unspecified	zlib	OS		
[CVE-2023-50387 ](https://security-tracker.debian.org/tracker/CVE-2023-50387)	 High	7.5	No	Unspecified	systemd	OS		
[CVE-2024-0553 ](https://security-tracker.debian.org/tracker/CVE-2024-0553)	 High	7.5	No	Unspecified	gnutls28	OS

**Comment by richlander** [comment]
Sorry for the delay, although it doesn't change the answer much.

- CVE-2024-0553 no longer applies to 8.0; still applies to 6.0
- All other CVEs are still active

The Debian tracker links state that the Debian versions we use are vulnerable / fixes are not yet available.

I took a quick look at the Ubuntu tracker. It appears like those images might be better. The same may be true of Alpine (although I didn't check). You might try scanning those instead.

**Comment by danieleforberghi** [comment]
But the image could be based on other Linux distros which not have that or install patches on top of mage. Or such. But you leave that to the user i assume.

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MichaelSimons** [comment]
> But the image could be based on other Linux distros which not have that or install patches on top of mage. Or such. But you leave that to the user i assume.

Changing the distro/version a .NET image is based on whole be a breaking change and would likely have a broad impact.  Please see .NET's [Image Update Policy](https://github.com/dotnet/dotnet-docker?tab=readme-ov-file#image-update-policy) for more details.

**Comment by danieleforberghi** [comment]
Ok have such a serious security risks is also a problem. That may need to be fixed.

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danieleforberghi** [comment]
Ok you are fixing patches but these 3 were missed. In the patching procedure. Or?

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by richlander** [comment]
I don't think fixes were "missed" by us. As far as I can tell, all available fixes are now in the images we produce. We make no claims on the status of fixes in the upstream distro beyond what is stated in the tracker pages you provided. 

We're a big believer in user choice. We ship Debian images by default. You are free to use Debian or one of the other distros we make available. All the tags are opt-in. The only difference is that the Debian tags are more convenient to use.

**Comment by danieleforberghi** [comment]
Ok but the image scanner in GCP indicates critical issues. But maybe you meant one of them where fixed in 8.0. The other are not Critical then you mean or. Depends on companies Security requirements if they do their own patches. But patching OS is common task for many companies. And it is possible to create custom images using dotnet SDK also of course. So dotnet SDK is not avaible in a distroless version or?

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by richlander** [comment]
Understand. We work with folks that care a lot about CVE scanning all the time. We try to help them with those goals within the context of what we can affect.

Yes, we have a distroless offering: https://devblogs.microsoft.com/dotnet/announcing-dotnet-chiseled-containers/

For anyone reading, here are the key skills to develop:

- Understand the full catalog of images that your upstream image provider produces. This includes distroless/chiseled.
- Learn how to read CVE tracker pages and the issues that they link to.
- Determine what options you have for self patching if upstream fixes are delayed.
- Develop a plan for what to do if patching isn't possible.

**Comment by lbussell** [comment]
You can follow the flowchart in our [Container Vulnerability Workflow](https://github.com/dotnet/dotnet-docker/blob/main/documentation/vulnerability-reporting.md) to determine if a given vulnerability will be addressed in our containers.

.NET 8 images are based on Debian 12 (Bookworm). .NET 6 images are based on Debian 11 (Bullseye) by default, but you can opt into Debian 12 with the `bookworm` tag:

- `mcr.microsoft.com/dotnet/aspnet:6.0-bookworm-slim`
- `mcr.microsoft.com/dotnet/sdk:6.0-bookworm-slim`

The state of these CVEs right now are: 

- [CVE-2023-45853](https://security-tracker.debian.org/tracker/CVE-2023-45853) is not fixed in Bullseye or Bookworm.
- [CVE-2023-50387](https://security-tracker.debian.org/tracker/CVE-2023-50387) is not fixed in Bullseye or Bookworm.
- [CVE-2024-0553](https://security-tracker.debian.org/tracker/CVE-2024-0553) is fixed in Bookworm but not Bullseye.

These all correspond to [branch K in the vulnerability workflow](https://github.com/dotnet/dotnet-docker/blob/main/documentation/vulnerability-reporting.md#k-wait-for-a-fix-to-be-available-from-the-linux-distro). We can't take any action if a fixed version of the package isn't available from the package repository of the Linux distro version. Sometimes fixes aren't ever made available because they are low severity or not applicable in container environments. Questions on this matter should be directed to the relevant Linux distro.
