### ISSUE TITLE
Missing images for 28 May 2024 Release

### ISSUE THREAD

**Issue by nesc58** [dotnet/dotnet-docker#5512]
Hi,
the nuget packages and also the setup files for linux and windows were released.
The docker images are still missing.

Are there any plans to provide docker images for this release?

Thank you

**Comment by lbussell** [comment]
Hi @nesc58, new images for .NET 8 and .NET 7 have been released:

```
$ docker run --rm mcr.microsoft.com/dotnet/runtime:8.0.6 dotnet --list-runtimes
Microsoft.NETCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Images for .NET 6 have been delayed due to a mis-match between our published checksums and the files that were published to blob storage. However, the only updates for this release [are a fix for WiX installers (Windows only) and an MSRC fix for Mac](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.31/6.0.31.md#wix-toolset-signed-with-incorrect-certificate). There are no functional or security changes for Linux, so you are not missing any features or security updates by staying on `6.0.30` tags while we work on the release.

**Comment by nesc58** [comment]
Thank you.
But mcr.microsoft.com/dotnet/aspnet:6.0.31 and mcr.microsoft.com/dotnet/sdk:6.0.423 are still missing.
The Images for 8.0.6 and 7.0.20 are available but not for the .net6 versions

**Comment by lbussell** [comment]
The .NET 6.0 images have now been published.

```
docker pull mcr.microsoft.com/dotnet/runtime:6.0.31
```

**Comment by austindrenski** [comment]
@lbussell any word on when the nightly images for these^ will be published?

```console
$ docker pull mcr.microsoft.com/dotnet/nightly/sdk:8.0.301-alpine3.19-aot
Error response from daemon: failed to resolve reference "mcr.microsoft.com/dotnet/nightly/sdk:8.0.301-alpine3.19-aot": mcr.microsoft.com/dotnet/nightly/sdk:8.0.301-alpine3.19-aot: not found
```

```console
$ docker pull mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0.6-alpine3.19-aot
Error response from daemon: failed to resolve reference "mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0.6-alpine3.19-aot": mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0.6-alpine3.19-aot: not found
```

**Comment by lbussell** [comment]
Hey @austindrenski, I just submitted the PR for those: https://github.com/dotnet/dotnet-docker/pull/5522

Since it's Friday afternoon, we'll most likely publish them Monday morning (PST) barring any issues.
