### ISSUE TITLE
Create some pre-seeded docker images.

### ISSUE THREAD

**Issue by Zoltu** [dotnet/dotnet-docker#57]
I would love to see a few docker images based on `microsoft/dotnet` that had their NuGet package cache preseeded with things like ASPNET Core, Entity Framework Core, etc.  Initially, just one pre-seeded docker image with all of the Microsoft stuff would be a good base, though it would be neat if there were a few variations (maybe one with ASPNET Core but not EntityFramework Core).

Not only will this greatly improve `dotnet restore` times, it will also reduce the size of my images on disk since all of my dotnet apps will share a common base image with most of the packages restored so their size will be predominately my source and any third-party stuff I depended on.

**Comment by Zoltu** [comment]
In case anyone wants to use it, I went ahead and did this for myself:
GitHub: https://github.com/Zoltu/docker-aspnetcore
DockerHub: https://hub.docker.com/r/zoltu/aspnetcore/

Feel free to submit PRs with additional libraries you want me to add, I don't mind the size of the image (within reason) because it makes all of my other docker images build *way* faster (few seconds instead of many minutes).

**Comment by MichaelSimons** [comment]
There is an [offline feature](https://github.com/dotnet/cli/pull/3485) being added to CLI which will help .NET Core Applications.  With this feature, the Dockerfile will need to be updated in order to trigger the cache to be built which happens on first use.

One potential problem that may arise the more packages that are added to the cache for ASPNET, Entity Framework, etc scenarios is that it is more likely not everyone will use or want all of these packages thus the images will be "bloated" with unnecessary artifacts.  At this point it may be better to have specialized images or leave this up to the individual users to create their own layers as appropriate on top of the base image.

**Comment by Zoltu** [comment]
If I could do something like this in my Dockerfile, I think it would fully alleviate the need for this.

```
FROM microsoft/dotnet

RUN dotnet seed Microsoft.AspNetCore.Mvc 1.0.0-rc2-final
RUN dotnet seed Microsoft.EntityFrameworkCore 1.0.0-rc2-final

COPY . /
RUN dotnet build

ENTRYPOINT [ "dotnet", "run" ]
```

Because the "seed" operations are before copying any files into the image, docker will cache the results of those lines so it won't require running more than once per docker host.

**Comment by MichaelSimons** [comment]
@Zoltu, Please log your request for a seed command within the [CLI repo](https://github.com/dotnet/cli).  This is where the command would need to be added.

**Comment by MichaelSimons** [comment]
The microsoft/dotnet images now come the the .NET core app packages cached.  Closing issue.
