### ISSUE TITLE
Git vulnerability CVE 2024-32002 found in dotnet/sdk:8.0.*

### ISSUE THREAD

**Issue by celeborne** [dotnet/dotnet-docker#5796]
We are using an instance of Aqua Scanner, and it has detected [CVE-2024-32002](https://nvd.nist.gov/vuln/detail/CVE-2024-32002), a vulnerability in git, in sdk:8.0

I have followed the [flowchart](https://github.com/dotnet/dotnet-docker/blob/main/documentation/vulnerability-reporting.md#r-log-an-issue-at-dotnetdotnet-docker) and believe this does meet the criteria for a fix.

The git version for all sdk:8.0 minor versions I have tested seems stuck at 2.39.2, and without additional manual config for adding GPG's and looking at PPA's forward of the base OS, this is still an issue.

git is explicitly installed by the dotnet dockerfile ([link to line](https://github.com/dotnet/dotnet-docker/blob/7d4d56941607d8521d500be152d66bb7d9e3dbf0/src/sdk/8.0/bookworm-slim/amd64/Dockerfile#L21)) using apt-get update && apt-get install.
A fixed version is available from [apk repositories](https://pkgs.alpinelinux.org/packages?name=git&branch=v3.19&repo=&arch=&maintainer=)

**Comment by lbussell** [comment]
Hey @celeborne, the default distro for .NET 8 images is Debian 12 "Bookworm". If you take a look at [CVE-2024-32002 on the Debian CVE Tracker](https://security-tracker.debian.org/tracker/CVE-2024-32002), you'll see that there isn't a fix available yet for Debian Bookworm.

The fix you are referring to is for Alpine Linux. `mcr.microsoft.com/dotnet/sdk:8.0-alpine` contains the fixed version of git that you refer to (`git-2.45.2-r0`).

I'm closing as not planned since there's no fix available from Debian. When the Debian base image is updated, or when a fix to [CVE-2024-32002](https://security-tracker.debian.org/tracker/CVE-2024-32002) is available in Debian Bookworm, then we'll rebuild the images.
