### ISSUE TITLE
powershell version 7.2.22 detected which is vulnerable. Part of CVE-2024-30045.

### ISSUE THREAD

**Issue by modi712** [dotnet/dotnet-docker#5854]
### Describe the Bug

We found a vulnerable package powershell 7.2.22 in base image mcr.microsoft.com/dotnet/sdk:6.0. It is reported as part of CVE-2024-30045 vulnerability.

### Steps to Reproduce

Pull mcr.microsoft.com/dotnet/sdk:6.0 and check for pwsh package. It will have powershell 7.2.22 installed which is vulnerable.

### Other Information

Even looking further at the code base we found this PowerShell version being used at multiple locations. Eg - [dotnet-docker/src/sdk/6.0/windowsservercore-ltsc2022/amd64/Dockerfile at main · dotnet/dotnet-docker (github.com)](https://github.com/dotnet/dotnet-docker/blob/main/src/sdk/6.0/windowsservercore-ltsc2022/amd64/Dockerfile), [dotnet-docker/src/sdk/6.0/cbl-mariner2.0/amd64/Dockerfile at main · dotnet/dotnet-docker (github.com)](https://github.com/dotnet/dotnet-docker/blob/main/src/sdk/6.0/cbl-mariner2.0/amd64/Dockerfile).

**Comment by lbussell** [comment]
Hi @modi712,

As described in the GitHub CVE report that you linked, CVE-2024-30045 was fixed in .NET Runtime version 8.0.5, and doesn't affect .NET 6. The version of PowerShell that's shipped in .NET images uses the .NET Runtime from the image, so since the latest images don't contain vulnerable versions of .NET, the PowerShell installation isn't vulnerable to this CVE either.

This seems to be an issue with your vulnerability scanner not detecting that we're running a framework-dependent deployment of PowerShell in the image.

**Comment by lbussell** [comment]
[Triage] The latest version of PowerShell will be included in this month's servicing release.

**Comment by mthalman** [comment]
Images have been published today which include PowerShell version 7.2.23 for the .NET 6 images. That version resolves this issue.

**Comment by modi712** [comment]
Hi @mthalman,

The version 7.2.23 is also vulnerable.

" CVE-2024-30045: A Remote Code Execution vulnerability exists in PowerShell where a stack buffer overrun occurs in .NET Double Parse routine.
Affected Versions:
PowerShell Version v7.2
PowerShell Version v7.4 prior to v7.4.3"

**Comment by mthalman** [comment]
That's interesting. As already [described above](https://github.com/dotnet/dotnet-docker/issues/5854#issuecomment-2331939828), there is no actual vulnerability here. It is a false positive due to the distribution of PowerShell that's included in the SDK image. In any case, there's no action we can take to resolve the false positive either since we have the latest available 7.2 version of PowerShell installed. I would recommend following up with PowerShell: https://github.com/PowerShell/PowerShell. When doing that, be sure to include what tool you are using that is reporting this vulnerability.
