### ISSUE TITLE
Don't use Release Tag `9.0` for a pre-release Version

### ISSUE THREAD

**Issue by alexanderlinne** [dotnet/dotnet-docker#5885]
### Describe the Bug

We use Renovate to Update our Software Dependencies. As #5873 states for the `9.0` Release Cycle, the Docker Tag `9.0-preview` has been changed to `9.0` for the *Release Candidate*. Since the Versions of the SDK itself still use a `-rc`-Postfix and we only update to release versions, we now face the issue that PRs for docker image updates are created without the corresponding updates to the SDK version ifself.

Is there any reason you are not using `9.0-rc.1` here?

**Comment by lbussell** [comment]
Hi @alexanderlinne, .NET 9 RC1 is fully supported for production use under "Go-Live" support ([support phases documentation](https://github.com/dotnet/core/blob/main/release-policies.md#support-phases)). .NET 9 has left the "Preview" support phase, so that's why we remove the `-preview` suffix from the tag. Publishing the `9.0` floating tag as soon as .NET 9 is supported gives early adopters a smoother transition to the GA release. We started following this pattern with .NET 8: https://github.com/dotnet/dotnet-docker/issues/4117.

I'm not sure exactly what criteria Renovate uses to decide when to update .NET versions. We also provide fixed `9.0.0-rc.1` (runtime/aspnet) and `9.0.100-rc.1` (SDK) tags in addition to the floating `9.0` tags. Since you're already using automated dependency updates, perhaps if you pinned to the latest .NET 8 fixed tags then Renovate would avoid updating to the .NET 9 RC1 fixed tag. Our supported tags documentation is [here](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-tags.md).

I did also check out the Renovate documentation and it looks like you could potentially set it up to avoid major version upgrades until you're ready to migrate to .NET 9 - https://docs.renovatebot.com/configuration-options/#matchupdatetypes.

**Comment by lbussell** [comment]
I'm closing this as not planned since we currently don't plan to make any changes here. We're happy to reconsider if we have enough engagement in the form of discussions/comments/upvotes on this issue.

I'll work on better documenting the Preview tags policy under the [supported tags](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-tags.md) documentation.
