### ISSUE TITLE
monitor/base repo is missing from featured repos list

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#5894]
The [Featured Repos list](https://github.com/dotnet/dotnet-docker?tab=readme-ov-file#featured-repos) is missing `monitor/base`.

**Comment by lbussell** [comment]
[Triage] The `dotnet/monitor` repo should be the preferred place to send users over the `dotnet/monitor/base` repo. The `base` repo should be intentionally left out of the "Featured Repos" list to keep the list simpler. The `dotnet/monitor` repo's "Usage" section should be updated to include a section about when to use `monitor` vs. `monitor/base`.

Closing as not planned since there's no issue with `monitor/base` being missing from the Featured Repos list. There should be a separate issue for updating the `monitor` Usage section (/cc @jander-msft).
