### ISSUE TITLE
Cryptographic functions using OpenSSL fail on Azure Kubernetes Service out-of-the-box when using 9.0-noble-chiseled-extra

### ISSUE THREAD

**Issue by davesheldon** [dotnet/dotnet-docker#6104]
### Describe the bug

I believe the issue I'm running into is similar to #5849. Essentially we have been using the aspnet:8.0-jammy-chiseled-extra image for our .NET 8 workloads in Azure Kubernetes Service. When we went to upgrade to .NET 9, we started running into a variety of OpenSSL errors (initialization errors, errors decoding public keys, etc). Here's an example from a service trying to decode an iText license at startup:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'iText.Licensing.Base.Util.SigningUtil' threw an exception.
 ---> iText.Licensing.Base.Exceptions.LicenseKeyException: Invalid public key.
 ---> Interop+Crypto+OpenSslCryptographicException: error:03000072:digital envelope routines::decode error
   at Interop.Crypto.DecodeSubjectPublicKeyInfo(ReadOnlySpan`1 source, EvpAlgorithmId algorithmId)
   at System.Security.Cryptography.RSAOpenSsl.ImportRSAPublicKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at System.Security.Cryptography.X509Certificates.OpenSslX509Encoder.BuildRsaPublicKey(Byte[] encodedData)
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPublicKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at iText.Licensing.Base.Util.CertificateWorker.CreateCertificateWorker(Stream certInputStream)... (truncated)
```

What I didn't see in the linked issue was any guidance on how to get past this issue. What should we be doing? We don't require FIPS (if indeed that is the issue here), so I'm not opposed to adding something to our Dockerfile to set a flag, but I would love some guidance on doing this the right way (e.g. if we did want FIPS enabled) or, alternatively, how to bypass it in a way that isn't super brittle.

Thanks!

### Which .NET image(s) are you using?

aspnet:9.0-noble-chiseled-extra

### Steps to reproduce

1. Create a linux pod on AKS using the above image. 
2. Have the pod run a crypto function, such as `SHA1.Create().ComputeHash("Hello World!")` as part of its workload
3. Observe the OpenSSL failure

### Output of `docker version`

```console

```

### Output of `docker info`

```console

```

**Comment by davesheldon** [comment]
I forgot to mention that this issue also persists in `aspnet:9.0-noble`, but not in the standard `aspnet:9.0` image.

**Comment by richlander** [comment]
Which nodepool host OS are you using?

**Comment by davesheldon** [comment]
Operating System: Azure Linux
Node Image Version: AKSAzureLinux-V2gen2fips-202411.12.0
Kubernetes Version: 1.30.5
Node Size: Standard_D16ads_v5

**Comment by richlander** [comment]
Thanks for that info. Very helpful.

Are you able to run on either .NET 8 or on the Debian images for the moment?

FYI: I asked relevant folks to look into this w/the details you provided.

**Comment by krwq** [comment]
@davesheldon can you try running docker with `-e OPENSSL_FORCE_FIPS_MODE=0`, if this is in fact same as https://github.com/dotnet/dotnet-docker/issues/5849 as I understand it that should fix this (assuming you don't care about FIPS compliance)

**Comment by krwq** [comment]
In case that doesn't help here is another thing to try out so we can at least get more details:
`export OPENSSL_TRACE=ALL`
and if that didn't print anything looking useful then on top of the above maybe:
`strace -f -e trace=all ./your_application` - this will be rather long but hopefully will contain something - you might want to avoid putting the output on github if you're running this on production since I can't guarantee if there will be anything in there which you might not want to accidentally share but you can possibly find what OpenSSL is doing exactly and have some more clues into what failed specifically.

**Comment by davesheldon** [comment]
Thanks for the suggestions. I’ll try them out today and report back. I’ll
have to ask my boss how important FIPS compliance is, but in case it is
required, what would be my next steps?

**Comment by krwq** [comment]
if `OPENSSL_FORCE_FIPS_MODE=0` works it means you're likely using some non-FIPS compliant algo. There are two likely cases:
- some algo used for creating a cert is weak (i.e. weak signature or hash algorithm) - this will require new cert since you cannot just change it as it would invalidate signatures - if it's self-signed cert this should be simple since you could just create a new one but most likely it's not
- PFX itself contains something weak (i.e. private key is strong but is encrypted with weak algo within PFX) which should be fixable because pfx itself is not signed (most of the time it's X509 + password encrypted private key with some PBKDF2 added to make it slow down anyone trying to brute force the password but it may be different especially when you use hardware security module or no password - there is no really one way to do it) - you can import cert and key from PFX within the non-FIPS environment (or use env var within FIPS env to override temporarily) and re-create pfx to fix this

**Comment by davesheldon** [comment]
Spoke some more with folks internally, and we are comfortable just switching to `9.0-azurelinux3.0-distroless-extra`, which seems to have the FIPS module and seems to work as expected.
