### ISSUE TITLE
Please add new tag of `sdk-alpine` and `runtime-alpine`

### ISSUE THREAD

**Issue by idoop** [dotnet/dotnet-docker#639]
Suggest:
Could you please add new tag of `sdk-alpine` and `runtime-alpine`? Just like tag of `sdk` and `runtime`.

**Comment by MichaelSimons** [comment]
@idoop - Could you help us understand the usage scenario in which you would find these tags helpful?

**Comment by idoop** [comment]
Yes, it's helpful.
I use .net core app and it's run in container. When I want update .net core sdk version,i also need update runtime version of docker image.This time,i only need use command `docker pull microsoft/dotnet:runtime-alpine` to update version without use command `docker tag microsoft/dotnet:xxx-runtime-alpine  microsoft/dotnet:runtime-alpine` , or i don't modify Jenkins job's script, because i use a template to match base image.

**Comment by MichaelSimons** [comment]
@idoop - To clarify, you are wanting an alpine tag that will get you the latest .NET Core runtime on the latest version of Alpine?  You do understand that your app could regress because of breaking changes introduced with new major/minor versions of .NET Core?  This is the reason why we don't currently provide this tag.  We feel it's usage is limited and not a recommended practice outside of a dev/test environment.

**Comment by MichaelSimons** [comment]
Closing issue
