### ISSUE TITLE
Consistent environment variable names for DOTNET_RUNNING_IN_CONTAINER

### ISSUE THREAD

**Issue by fbeltrao** [dotnet/dotnet-docker#677]
## Steps to reproduce the issue
1. Build .NET Core application based on microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709
2. Build .NET Core application based on microsoft/dotnet:2.1-aspnetcore-runtime
3. Verify that nano server uses DOTNET_RUNNING_IN_CONTAINERS while the later uses DOTNET_RUNNING_IN_CONTAINER

## Expected behavior
Both base image define the same environment variable name

## Actual behavior
They have distinct environment variable names

## Reference files
https://github.com/dotnet/dotnet-docker/blob/master/2.1/aspnetcore-runtime/nanoserver-1709/amd64/Dockerfile#L36
https://github.com/dotnet/dotnet-docker/blob/master/2.1/runtime-deps/stretch-slim/amd64/Dockerfile#L21

My proposed solution would be to change all windows based images to use DOTNET_RUNNING_IN_CONTAINER (singular). See them [here](https://github.com/dotnet/dotnet-docker/search?q=DOTNET_RUNNING_IN_CONTAINERS&type=Code)

I have created [PR 678](https://github.com/dotnet/dotnet-docker/pull/678) as an optional solution.

**Comment by MichaelSimons** [comment]
@fbeltrao - Thanks for logging this issue.  When fixing this, I don't think we should be simply renaming the existing variable in the nanoserver images to be singular.  As you noted in the PR this is considered a breaking change.  

Since 2.1 is going to be LTSC, I am in favor of adding the singular version.  In the 2.2 images (which are in preview) and going forward, we can make the correction so that there is only on variable.
