### ISSUE TITLE
[nightly] Enable tests for 3.0 images 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#692]
The tests for the 3.0 images are currently disabled because the product e2e experience for 3.0 is not yet complete.  For example you cannot use `dotnet new` to create a project that targets 3.0.  Once this is supported, the tests should be enabled - see https://github.com/dotnet/dotnet-docker/blob/nightly/tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs#L133

**Comment by puhovalexey** [comment]
@MichaelSimons I'm building a pipeline to early test sdk 3.0 and when I run/build/publish any application I see:
`C:\Program Files\dotnet\sdk\3.0.100-preview-009756\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(294,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [C:\test\test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview-009756\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(294,5): error MSB4018: System.EntryPointNotFoundException: Unable to find an entry point named 'BeginUpdateResource' in DLL 'Kernel32'. [C:\test\test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview-009756\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(294,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater.Kernel32.BeginUpdateResource(String pFileName, Boolean bDeleteExistingResources) [C:\test\test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview-009756\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(294,5): error MSB4018:    at Microsoft.NET.Build.Tasks.AppHost.Create(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String intermediateAssembly, Logger log) in /_/src/Tasks/Microsoft.NET.Build.Tasks/AppHost.cs:line 82 [C:\test\test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview-009756\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(294,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() in /_/src/Tasks/Microsoft.NET.Build.Tasks/CreateAppHost.cs:line 38 [C:\test\test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview-009756\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(294,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 35 [C:\test\test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview-009756\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(294,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\test\test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview-009756\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(294,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\test\test.csproj]`

Do you know if that's expected because of the issue above or should I create a new one?

**Comment by MichaelSimons** [comment]
@puhovalexey - Are you encountering this with the nanoserver images?  It looks like you may be hitting this issue - https://github.com/dotnet/sdk/issues/2652.

**Comment by puhovalexey** [comment]
@MichaelSimons exactly! Didn't figure out to search for this issue in sdk repo. Thank you for the reference
