### ISSUE TITLE
1.0.0-preview2-sdk Appears To Come With Wrong Version of  Microsoft.NETCore.App

### ISSUE THREAD

**Issue by StrangeWill** [dotnet/dotnet-docker#72]
> web_1 | Project MyProject (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
> web_1 | The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc2-3002702' was not found.
> web_1 |   - Check application dependencies and target a framework version installed at:
> web_1 |       /usr/share/dotnet/shared/Microsoft.NETCore.App
> web_1 |   - The following versions are installed:
> web_1 |       1.0.0
> web_1 |   - Alternatively, install the framework version '1.0.0-rc2-3002702'.

This is a project developed on Visual Studio 2015 on Windows and pulled into a container, when I run `dotnet new` it wants to use Microsoft.NETCore.App 1.0.0 that came with the container, but Visual Studio wants to use 1.0.0-rc2-3002702. Why the discrepancy?

Unfortunately it appears 1.0.0 takes precedence over 1.0.0-rc2-3002702 and the rc2 version will not be pulled during a `dotnet restore`.

**Comment by naamunds** [comment]
This issue is due to a version mismatch between the .NET Core installation on your Windows machine and the .NET Core installation on your Docker container. There are a couple ways you could work around this:

- Use a Docker container with the older version of .NET.  I believe that the microsoft/dotnet:1.0.0-preview1 image would work.
- Upgrade your app to use the newer version of .NET which is installed in your Docker container. This version hasn't yet been released in a Visual Studio tooling bundle, but you could upgrade the project by manually editing its project.json.  You can see what a project.json file containing the new versions of the framework and dependencies would look like by doing `dotnet new` in a separate directory.

**Comment by StrangeWill** [comment]
Yeah, now I feel dumb, should have noticed that Visual Studio uses _preview1_ and that preview2 != RC2.

All seems good.
