### ISSUE TITLE
COPY failed: no source files were specified

### ISSUE THREAD

**Issue by warheat1990** [dotnet/dotnet-docker#750]
I have a project with structure like this

```
    |--.dockerignore
    |--Dockerfile
    |--SanSa.sln
    |--SanSa.Web (folder)  
       |--SanSa.Web.csproj
    |--SanSa.WebAdmin (folder)  
       |--SanSa.WebAdmin.csproj
    |--SanSa.DataAccess (folder)  
       |--SanSa.DataAccess.csproj
```

I'm trying to deploy SanSa.Web, my Dockerfile content is as follows

```
FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Sansa.Web/*.csproj ./SanSa.Web/
RUN dotnet restore

# copy everything else and build app
COPY SanSa.Web/. ./SanSa.Web/
WORKDIR /app/SanSa.Web
RUN dotnet publish -c Release -o out


FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/SanSa.Web/out ./
ENTRYPOINT ["dotnet", "SanSa.Web.dll"]
```

My .ignoredocker
```
# directories
**/bin/
**/obj/
**/out/

# files
Dockerfile*
**/*.trx
**/*.md
```

When I run `docker build --tag sansa:latest -f Dockerfile .` I got this error 

```
Step 4/12 : COPY SanSa/*.csproj ./SanSa/
COPY failed: no source files were specified
```

Any idea why?

**Comment by omajid** [comment]
(This sounds like a question well-suited for stackoverflow rather than the dotnet issue tracker)

> Step 4/12 : COPY SanSa/*.csproj ./SanSa/

The error says that you are trying to copy all the `.csproj` files from `SanSa` directory. And no such files exist. You don't have a `SanSa` directory, so that's kind of expected. But this `COPY` instruction doesn't match the contents of your `Dockerfile`. Are you sure you are looking at the right files?

**Comment by MichaelSimons** [comment]
In addition to what @omajid said, the provided Dockerfile doesn't appear to match the error output.

Step 4 from the provided Dockerfile

```
COPY Sansa.Web/*.csproj ./SanSa.Web/
```

Provided build output:

```
Step 4/12 : COPY SanSa/*.csproj ./SanSa/
COPY failed: no source files were specified
```

Note the difference in the presence of `.Web`.

The casing of `Sansa` in the provided Dockerfile doesn't match the provided directory structure.  If you are using a case sensitive file system, this may be the source of your problem.

Closing as this is not a product issue with the microsoft/dotnet images.

**Comment by sunainadevi1998** [comment]
FROM mcr.microsoft.com/dotnet/sdk:5.0 As build
WORKDIR /app
COPY *.sln .
COPY ExamRoom.ItemBanking./*.csproj ./ExamRoom.ItemBanking/
RUN dotnet restore
COPY ExamRoom.ItemBanking/. ./ExamRoom.ItemBanking/
WORKDIR /app/ExamRoom.ItemBanking
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build /app/ExamRoom.ItemBanking/out ./
ENTRYPOINT ["dotnet", "ExamRoom.ItemBanking.dll"]

facing same issue any suggestions

**Comment by mthalman** [comment]
@sunainadevi1998 - Please submit your question at https://github.com/dotnet/dotnet-docker/discussions. This is a long-closed issue of a general Docker error message. Each environment is different as to the reason for the error but it all comes down to incorrect configuration. In order to get the best response, it's better to open a new discussion and providing as many details as possible, including repo steps.
