### ISSUE TITLE
So is this at 1.0, or 1.0 preview?

### ISSUE THREAD

**Issue by Lewiscowles1986** [dotnet/dotnet-docker#81]
Looks like in all the hype either version numbers were not updated or version strings were selected that are confusing. If this is a release, why not use semantic versioning and update the patch or minor release version? using names like preview sounds a lot like a release candidate by any other name.

**Comment by MichaelSimons** [comment]
@Lewiscowles1986, I apologize for the confusion.  I copied a snippet from the [.NET Core announement](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/).

## Distributions
There are two main distributions for .NET Core:

.NET Core – Includes the .NET Core runtime and framework. The current version is “.NET Core 1.0”
.NET Core SDK – Includes .NET Core and the .NET Core Tools. The current version is “.NET Core SDK 1.0 Preview 2”.

The .NET Core Tools are considered “Preview” currently. We chose “Preview” because we are not yet done shaping the tools. We know that there are still some changes coming. It’s not a quality statement. We’re quite happy with the quality and use the .NET Core tools ever day as part of our engineering system.


To answer your question, the development or tools images are 1.0.0-preview and the runtime images are 1.0.0

**Comment by Lewiscowles1986** [comment]
Thanks. I feel like I was reading all the wrong things, winding myself up...
