### ISSUE TITLE
Reevalute workaround for non-root user issue with NuGetScratch

### ISSUE THREAD

**Issue by naamunds** [dotnet/dotnet-docker#84]
As a workaround for https://github.com/dotnet/dotnet-docker/issues/78, a fix was submitted which removes the /tmp/NuGetScratch directory.  The root cause of this issue is https://github.com/NuGet/Home/issues/2793, so when that issue is fixed, the workaround here should be reevaluated.

Depending on the fix made in NuGet, we may want to remove the workaround in this repo.  Alternatively, we may want to keep this behavior and also remove the NuGetScratch directory in the Windows images to reduce the size of the Docker images, similar to the removal of the apt-get caches.

**Comment by acastaner** [comment]
Just some extra feedback on this. Removing /tmp/NuGetScratch kind of works but if the systems uses different users to run dotnet apps then you'll run into the same issue: user one might re-create /tmp/NuGetScratch and own it, but then user 2 won't have access to it.

The workaround would be to have each user in a common group I guess but that kind of goes against the least privilege security policy of many enterprises.

**Comment by MichaelSimons** [comment]
NuGet has addressed the underlying issue on their side.  Additionally the CLI no longer uses NuGet to initialize the package cache therefore the SDK Dockerfiles don't even trigger the creation of the NuGetScratch dir.  The logic to cleanup the NuGet local temp dir should be removed because it doesn't do anything.
