### ISSUE TITLE
Getting an error when doing a docker pull in windows container on ACS

### ISSUE THREAD

**Issue by sauryadas** [dotnet/dotnet-docker#86]
![image](https://cloud.githubusercontent.com/assets/15387759/17047048/76ec1f12-4f8e-11e6-81dd-ee4f036d3566.png)
@MichaelSimons  any idea ?

**Comment by colemickens** [comment]
Guessing it's an Azure VM? What image did you deploy? Is it a relatively clean VM?

**Comment by sauryadas** [comment]
Windows swarm cluster on ACS.

**Comment by MichaelSimons** [comment]
@sauryadas - Is this issue specific to the microsoft/dotnet images?  Are you able to pull other images (e.g. debian:jessie)?

**Comment by MichaelSimons** [comment]
@sauryadas - Any update on this?  Can you answer my previous questions?

**Comment by sauryadas** [comment]
@MichaelSimons the base image is windows server 2016 tp5 . I was able to pull Microsoft/iis

**Comment by MichaelSimons** [comment]
@sauryadas, Can you clarify what you mean by the "base image is windows server 2016 tp5"?  Do you mean Windows Server 2016 TP5 is your Docker host environment?  I assume so since you successfully pulled the Microsoft/iis image.  If that is the case, then I believe the issue is that you are trying to pull the wrong microsoft/dotnet image.  From the screen shot you included it looks like you are using microsoft/dotnet:latest.  This is the Debian based image which cannot be run on Windows Containers.  You need to use the microsoft/dotnet:windowsservercore image.

**Comment by sauryadas** [comment]
@MichaelSimons oops .. i assumed this is all windows... i was able to run the various version of the images .. closing this now. thanks

**Comment by MichaelSimons** [comment]
@sauryadas, FYI Docker is working a feature that will support multi-platform for a single tag.  This will allow you to pull microsoft/dotnet:latest and depending on the platform you are calling from, the appropriate image will get pulled.  In the meantime, we have to rely on separate tags.
