### ISSUE TITLE
Nuget credential provider is built in with SDK docker images

### ISSUE THREAD

**Issue by shubham90** [dotnet/dotnet-docker#878]
## Steps to reproduce the issue
The[ artifacts credential provider ](https://github.com/Microsoft/artifacts-credprovider) should be included in SDK docker images by default. 
## Expected behavior
Dotnet sdk image download already contains credential provider. 

## Actual behavior
Today, we need to add a separate step adding cred provider

## Additional information (e.g. issue happens only occasionally)
Only in images where SDK version is > 2.1.500
I am happy to contribute if this is triaged.

**Comment by wesley-pattison** [comment]
Any update on this? I was expecting with the release of 2.2 SDK image this would be resolved.

**Comment by moisoiu** [comment]
@shubham90 Can you please tell me how did you manage to make it work on your implementation?

**Comment by shubham90** [comment]
@moisoiu what scenario are you trying to implement? Acquisition of cred provider on dotnet docker images or use of cred provider in docker containers generally?

**Comment by moisoiu** [comment]
> @moisoiu what scenario are you trying to implement? Acquisition of cred provider on dotnet docker images or use of cred provider in docker containers generally?

Hi @shubham90  I would say both, and somehow I've managed to install the microsoft cred provided but still it seems that I can't connect to my private TFS nugget packager.

I've post the docker image and nuget.config on the link below
[https://github.com/Microsoft/artifacts-credprovider/issues/63](url)

**Comment by shubham90** [comment]
I have replied to you on that thread. let's use that thread to discuss your issue.

**Comment by pleandre** [comment]
Hello,

Our build server doesn't have direct access to internet, and we need to use a nexus proxy to download all nuget packages, docker images, etc.

Therefore it seems difficult to execute the following script in our Dockerfile: 
https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh

Do you plan to include this plugin by default in the next release of dotnet core sdk docker image ?
Regards,
Pierre

**Comment by MichaelSimons** [comment]
This was discussed at length and a decision was made to not include the _Azure Artifacts Credential Provider_ within the .NET Core SDK images at this time.  There is active work on improving the overall installation experience for the Cred Provider including adding a .NET Core global tool experience which will make it easier to install in a derived image.  

Some factors that went into the decision were:

* Adding the Cred Provider isn't something everyone would want.  We want to maintain a high bar for what goes into the image in order to keep the size manageable and generally appealing as a base image for everyone to use.
* Having to support versions of the cred provider for the lifetime of a .NET Core ltsc release.
* The NuGet plugin infrastructure currently has some limitations/bugs with ARM.  The .NET images should have content/behavior parity across the supported platforms.  Work will continue to address this but it will take some time.

**Comment by dennis-yemelyanov** [comment]
Is it gone in SDK 3.1? https://github.com/dotnet/dotnet-docker/blob/master/3.1/sdk/buster/amd64/Dockerfile doesn't seem to have any instruction to install Nuget credential provider

**Comment by mthalman** [comment]
> Is it gone in SDK 3.1? https://github.com/dotnet/dotnet-docker/blob/master/3.1/sdk/buster/amd64/Dockerfile doesn't seem to have any instruction to install Nuget credential provider

It was never there.  The decision was made to not implement this.  See https://github.com/dotnet/dotnet-docker/issues/878#issuecomment-513978346

**Comment by dennis-yemelyanov** [comment]
ah thank you for clarifying this. The PR above to add it to 2.1 SDK appeared to have been merged, so I didn't bother to read the comments.

Got confused since this sample file mentions that the installation should eventually become optional: https://github.com/microsoft/artifacts-credprovider/blob/2011609bec3b123527e5bf58c76adbda696625ce/samples/dockerfile.sample.txt#L6

Will follow up with the artifacts-credprovider repository to remove the misleading comment
