### ISSUE TITLE
Clair scanner produces over 300 vulnerabilities

### ISSUE THREAD

**Issue by AtlanteanTec** [dotnet/dotnet-docker#924]
## Steps to reproduce the issue
1. Create a docker image from microsoft/dotnet:2-aspnetcore-runtime.
2. Run Clair scanner on the resulting image.

## Expected behavior
Container should be secure.

## Actual behavior
Clair scanner shows the following vulnerabilities with the following packages:

```
glibc
systemd
libgc
linux
libidn
shadowlibtasn1-6
util-linux
libxml2
binutils
sqlite3
gnutls28
cron
unzip
policykit-1
elfutils
krb5
mariadb-10.1
openssh
ncurses
gnupg2
nghttp2
nettle
glib2.0
vim
tar
patch
python3.5
python2.7
openldap
openssl
pcre3
coreutils
libgcrypt20
sudo
krb5
libxslt
perl
expat
xdg-user-dirs
iptables
net-tools
gnupg2
apt
```

I have attached the log with all the vulnerabilities that I found.

[ClairScannerErrorLog.txt](https://github.com/dotnet/dotnet-docker/files/2836987/ClairScannerErrorLog.txt)

**Comment by MichaelSimons** [comment]
We monitor vulnerabilities in various Linux base images. We have noticed that Debian and other distros typically have >0 reported vulnerabilities. We have also noticed that Alpine typically has 0 reported vulnerabilities. We offer images for Debian, Ubuntu and Alpine. As a result, you've got choices available for picking whatever is your preferred distribution.

We also provide same-day updates of .NET Core images whenever the underlying Linux base image is updated. As a result, .NET Core docker images are as good as they can be w/rt the vulnerabilities you are seeing. There is no action that we are aware of to improve on this situation for Debian.

We recommend Alpine. We believe that it is the best choice for most users because it offers much smaller size, a much lower (as I said, typically 0) reported vulnerability surface area, and doesn't have significant downsides (except compatibility with other distros).

Does that help?

Related to #895

cc @richlander
